export interface CityItem {
    w: string;
    es: string;
    id: string;
    hex: string;
    type: 'base' | 'object';
    req?: string[];
    enS: string;
    esS: string;
    tts?: string;
    ttsS?: string;
}

export const CATALOG: Record<string, CityItem[]> = {
    'Infrastructure': [
        { w: 'Road', es: 'Calle', id: 'road', hex: '1f6e3', type: 'base', enS: 'Cars drive on the road.', esS: 'Los autos conducen por la calle.' },
        { w: 'Sidewalk', es: 'Acera', id: 'sidewalk', hex: '1f6b6', type: 'base', enS: 'People walk on the sidewalk.', esS: 'La gente camina por la acera.' },
        { w: 'Bridge', es: 'Puente', id: 'bridge', hex: '1f309', type: 'base', enS: 'The bridge crosses the river.', esS: 'El puente cruza el río.' },
        { w: 'Highway', es: 'Autopista', id: 'highway', hex: '1f6e3', type: 'base', enS: 'The highway is very fast.', esS: 'La autopista es muy rápida.' },
        { w: 'Tunnel', es: 'Túnel', id: 'tunnel', hex: '1f687', type: 'object', req: ['mountain', 'grass'], enS: 'The train goes through the tunnel.', esS: 'El tren pasa por el túnel.' },
        { w: 'Street Light', es: 'Farola', id: 'light', hex: '1f4a1', type: 'object', req: ['road', 'sidewalk'], enS: 'The light shines at night.', esS: 'La luz brilla por la noche.' },
        { w: 'Traffic Light', es: 'Semáforo', id: 'traffic', hex: '1f6a5', type: 'object', req: ['road'], enS: 'The light turns red.', esS: 'La luz se pone roja.' },
        { w: 'Hydrant', es: 'Hidrante', id: 'hydrant', hex: '1f9ef', type: 'object', req: ['sidewalk', 'road'], enS: 'Firefighters use the hydrant.', esS: 'Los bomberos usan el hidrante.' },
        { w: 'Parking', es: 'Estacionamiento', id: 'parking', hex: '1f17f', type: 'base', enS: 'Park your car here.', esS: 'Estaciona tu auto aquí.' },
        { w: 'Gas Station', es: 'Gasolinera', id: 'gas', hex: '26fd', type: 'object', req: ['road'], enS: 'Fill the tank with gas.', esS: 'Llena el tanque con gasolina.' },
        { w: 'Bench', es: 'Banca', id: 'bench', hex: '1fa91', type: 'object', req: ['park', 'sidewalk'], enS: 'Sit on the bench.', esS: 'Siéntate en la banca.' },
        { w: 'Trash Can', es: 'Basurero', id: 'trash', hex: '1f5d1', type: 'object', req: ['sidewalk', 'park'], enS: 'Throw the trash away.', esS: 'Tira la basura.' },
        { w: 'Billboard', es: 'Cartelera', id: 'billboard', hex: '1f5bc', type: 'object', req: ['road', 'office'], enS: 'The billboard is colorful.', esS: 'La cartelera es colorida.' },
        { w: 'Fence', es: 'Cerca', id: 'fence', hex: '1f6a7', type: 'object', req: ['grass', 'house'], enS: 'The fence is around the yard.', esS: 'La cerca está alrededor del patio.' },
        { w: 'Mailbox', es: 'Buzón', id: 'mailbox', hex: '1f4eb', type: 'object', req: ['sidewalk', 'house'], enS: 'Check the mailbox for letters.', esS: 'Revisa el buzón por cartas.' },
        { w: 'Fire Hydrant', es: 'Hidrante', id: 'hydrant2', hex: '1f9ef', type: 'object', req: ['road'], enS: 'The red hydrant has water.', esS: 'El hidrante rojo tiene agua.' },
        { w: 'Zebra Crossing', es: 'Paso de cebra', id: 'zebra', hex: '1f6b6', type: 'base', enS: 'Cross the street here.', esS: 'Cruza la calle aquí.' },
        { w: 'Stop Sign', es: 'Señal de alto', id: 'stop', hex: '1f6d1', type: 'object', req: ['road'], enS: 'Cars must stop here.', esS: 'Los autos deben parar aquí.' },
        { w: 'Statue', es: 'Estatua', id: 'statue', hex: '1f5fd', type: 'object', req: ['park', 'square'], enS: 'A big statue in the park.', esS: 'Una gran estatua en el parque.' },
        { w: 'Town Square', es: 'Plaza', id: 'square', hex: '1f3d9', type: 'base', enS: 'Meet your friends in the square.', esS: 'Encuentra a tus amigos en la plaza.' },
    ],
    'Buildings': [
        { w: 'House', es: 'Casa', id: 'house', hex: '1f3e1', type: 'object', req: ['grass'], enS: 'My family lives in a house.', esS: 'Mi familia vive en una casa.', ttsS: 'My family livs in a house.' },
        { w: 'Apartment', es: 'Apartamento', id: 'apt', hex: '1f3e2', type: 'object', req: ['grass'], enS: 'Many people live in apartments.', esS: 'Mucha gente vive en apartamentos.', ttsS: 'Many people liv in apartments.' },
        { w: 'School', es: 'Escuela', id: 'school', hex: '1f3eb', type: 'object', req: ['grass', 'park'], enS: 'Children learn at school.', esS: 'Los niños aprenden en la escuela.' },
        { w: 'Hospital', es: 'Hospital', id: 'hosp', hex: '1f3e5', type: 'object', req: ['grass'], enS: 'Doctors work at the hospital.', esS: 'Los doctores trabajan en el hospital.' },
        { w: 'Post Office', es: 'Correo', id: 'post', hex: '1f3e3', type: 'object', req: ['grass'], enS: 'Send a letter at the post office.', esS: 'Envía una carta en el correo.' },
        { w: 'Bank', es: 'Banco', id: 'bank', hex: '1f3e6', type: 'object', req: ['grass'], enS: 'Manage your Nova Card and pay your debt at the bank.', esS: 'Maneja tu Tarjeta Nova y paga tu deuda en el banco.' },
        { w: 'Library', es: 'Biblioteca', id: 'lib', hex: '1f4da', type: 'object', req: ['grass'], enS: 'Read books at the library.', esS: 'Lee libros en la biblioteca.' },
        { w: 'Hotel', es: 'Hotel', id: 'hotel', hex: '1f3e8', type: 'object', req: ['grass'], enS: 'Travelers stay at a hotel.', esS: 'Los viajeros se quedan en un hotel.' },
        { w: 'Cinema', es: 'Cine', id: 'movie', hex: '1f3a6', type: 'object', req: ['grass'], enS: 'Watch a movie at the cinema.', esS: 'Mira una película en el cine.' },
        { w: 'Stadium', es: 'Estadio', id: 'stadium', hex: '1f3df', type: 'object', req: ['grass'], enS: 'Play soccer at the stadium.', esS: 'Juega fútbol en el estadio.' },
        { w: 'Museum', es: 'Museo', id: 'museum', hex: '1f3db', type: 'object', req: ['grass'], enS: 'See art at the museum.', esS: 'Mira arte en el museo.' },
        { w: 'Church', es: 'Iglesia', id: 'church', hex: '26ea', type: 'object', req: ['grass'], enS: 'The church has a bell.', esS: 'La iglesia tiene una campana.' },
        { w: 'Factory', es: 'Fábrica', id: 'factory', hex: '1f3ed', type: 'object', req: ['grass'], enS: 'They build toys in the factory.', esS: 'Construyen juguetes en la fábrica.' },
        { w: 'Skyscraper', es: 'Rascacielos', id: 'office', hex: '1f3d9', type: 'object', req: ['grass'], enS: 'Skyscrapers touch the clouds.', esS: 'Los rascacielos tocan las nubes.' },
        { w: 'Castle', es: 'Castillo', id: 'castle', hex: '1f3ef', type: 'object', req: ['grass', 'mountain'], enS: 'Kings live in a castle.', esS: 'Los reyes viven en un castillo.', ttsS: 'Kings liv in a castle.' },
        { w: 'Observatory', es: 'Observatorio', id: 'obs', hex: '1f52d', type: 'object', req: ['mountain'], enS: 'Look at stars from the observatory.', esS: 'Mira las estrellas desde el observatorio.' },
        { w: 'Tent', es: 'Tienda de campaña', id: 'tent', hex: '26fa', type: 'object', req: ['park', 'grass'], enS: 'Sleep in a tent while camping.', esS: 'Duerme en una tienda al acampar.' },
        { w: 'Barn', es: 'Granero', id: 'barn', hex: '1f3dc', type: 'object', req: ['grass'], enS: 'The barn is for the cows.', esS: 'El granero es para las vacas.' },
        { w: 'Temple', es: 'Templo', id: 'temple', hex: '1f3ef', type: 'object', req: ['grass'], enS: 'The temple is peaceful.', esS: 'El templo es tranquilo.' },
        { w: 'Fountain', es: 'Fuente', id: 'fount', hex: '26f2', type: 'object', req: ['park', 'square'], enS: 'The water splashes.', esS: 'El agua salpica.' },
        { w: 'Monument', es: 'Monumento', id: 'monu', hex: '1f5fd', type: 'object', req: ['square'], enS: 'A historical place.', esS: 'Un lugar histórico.' },
        { w: 'Escalator', es: 'Escalera eléctrica', id: 'esca', hex: '1f6dd', type: 'object', req: ['office', 'mall'], enS: 'Going up and down.', esS: 'Subiendo y bajando.' },
        { w: 'Elevator', es: 'Elevador', id: 'elev', hex: '1f6d7', type: 'object', req: ['office', 'apt'], enS: 'Fast lift to top.', esS: 'Subida rápida al tope.' },
        { w: 'Flag', es: 'Bandera', id: 'flag', hex: '1f3f4', type: 'object', req: ['school', 'stadium'], enS: 'Wave the flag.', esS: 'Ondea la bandera.' },
        { w: 'Shop', es: 'Tienda', id: 'shop', hex: '1f3ea', type: 'object', req: ['grass', 'road'], enS: 'Buy food at the shop.', esS: 'Compra comida en la tienda.' },
        { w: 'Fire Station', es: 'Estación de bomberos', id: 'fire_st', hex: '1f692', type: 'object', req: ['road'], enS: 'Fire trucks stay here.', esS: 'Los camiones de bomberos están aquí.' },
        { w: 'Police Station', es: 'Estación de policía', id: 'pol_st', hex: '1f693', type: 'object', req: ['road'], enS: 'Police officers work here.', esS: 'Los policías trabajan aquí.' },
        { w: 'Greenhouse', es: 'Invernadero', id: 'greenh', hex: '1f3e1', type: 'object', req: ['park', 'grass'], enS: 'Plants grow in the greenhouse.', esS: 'Las plantas crecen en el invernadero.' },
        { w: 'Windmill', es: 'Molino', id: 'windm', hex: '1f3db', type: 'object', req: ['grass', 'field'], enS: 'The windmill turns fast.', esS: 'El molino gira rápido.' },
        { w: 'Warehouse', es: 'Almacén', id: 'ware', hex: '1f3ed', type: 'object', req: ['road'], enS: 'A big building for boxes.', esS: 'Un edificio grande para cajas.' },
        { w: 'Mosque', es: 'Mezquita', id: 'mosque', hex: '1f54c', type: 'object', req: ['grass'], enS: 'The mosque has a dome.', esS: 'La mezquita tiene una cúpula.' },
        { w: 'Synagogue', es: 'Sinagoga', id: 'syna', hex: '1f54d', type: 'object', req: ['grass'], enS: 'A place of worship.', esS: 'Un lugar de oración.' },
        { w: 'Theater', es: 'Teatro', id: 'theater', hex: '1f3ad', type: 'object', req: ['grass'], enS: 'The theater has a stage.', esS: 'El teatro tiene un escenario.' },
        { w: 'Mall', es: 'Centro comercial', id: 'mall', hex: '1f6cd', type: 'object', req: ['road'], enS: 'Let’s go shopping at the mall.', esS: 'Vamos de compras al centro comercial.' },
        { w: 'Gym', es: 'Gimnasio', id: 'gym', hex: '1f3cb', type: 'object', req: ['grass'], enS: 'I exercise at the gym.', esS: 'Hago ejercicio en el gimnasio.' },
        { w: 'Airport', es: 'Aeropuerto', id: 'airport', hex: '2708', type: 'object', req: ['grass'], enS: 'Airplanes land at the airport.', esS: 'Los aviones aterrizan en el aeropuerto.' },
        { w: 'Train Station', es: 'Estación de tren', id: 't_station', hex: '1f689', type: 'object', req: ['road'], enS: 'The train is at the station.', esS: 'El tren está en la estación.' },
        { w: 'Bus Station', es: 'Parada de autobús', id: 'b_station', hex: '1f68f', type: 'object', req: ['road'], enS: 'Wait for the bus here.', esS: 'Espera el autobús aquí.' },
        { w: 'Supermarket', es: 'Supermercado', id: 'super2', hex: '1f6d2', type: 'object', req: ['road'], enS: 'Buy milk at the supermarket.', esS: 'Compra leche en el supermercado.' },
        { w: 'Bakery', es: 'Panadería', id: 'bakery2', hex: '1f956', type: 'object', req: ['sidewalk'], enS: 'I smell fresh bread.', esS: 'Huelo el pan fresco.' },
        { w: 'Pharmacy', es: 'Farmacia', id: 'rx2', hex: '1f48a', type: 'object', req: ['sidewalk'], enS: 'Buy medicine here.', esS: 'Compra medicina aquí.' },
        { w: 'Barber Shop', es: 'Barbería', id: 'hair2', hex: '1f488', type: 'object', req: ['sidewalk'], enS: 'Cut your hair at the barber.', esS: 'Corta tu cabello en la barbería.' },
        { w: 'Bookstore', es: 'Librería', id: 'bookstore2', hex: '1f4da', type: 'object', req: ['sidewalk'], enS: 'Many books in the store.', esS: 'Muchos libros en la tienda.' },
        { w: 'Toy Store', es: 'Juguetería', id: 'toy2', hex: '1f9f8', type: 'object', req: ['sidewalk'], enS: 'Buy a new toy.', esS: 'Compra un juguete nuevo.' },
        { w: 'Pet Shop', es: 'Tienda de mascotas', id: 'pet2', hex: '1f436', type: 'object', req: ['sidewalk'], enS: 'The puppies are cute.', esS: 'Los cachorros son lindos.' },
        { w: 'University', es: 'Universidad', id: 'uni2', hex: '1f3db', type: 'object', req: ['grass'], enS: 'I study at the university.', esS: 'Estudio en la universidad.' },
        { w: 'Science Center', es: 'Centro de ciencia', id: 'sci_c', hex: '1f52c', type: 'object', req: ['grass'], enS: 'We do experiments here.', esS: 'Hacemos experimentos aquí.' },
        { w: 'Skyscraper', es: 'Rascacielos', id: 'sky_sc', hex: '1f3ec', type: 'object', req: ['office', 'road'], enS: 'It is a very tall building.', esS: 'Es un edificio muy alto.' },
    ],
    'School & Learning': [
        { w: 'Backpack', es: 'Mochila', id: 'bp2', hex: '1f392', type: 'object', req: ['school'], enS: 'Put your books in the backpack.', esS: 'Pon tus libros en la mochila.' },
        { w: 'Pencil', es: 'Lápiz', id: 'pen2', hex: '270f', type: 'object', req: ['school'], enS: 'Write with your pencil.', esS: 'Escribe con tu lápiz.' },
        { w: 'Notebook', es: 'Cuaderno', id: 'note', hex: '1f4d3', type: 'object', req: ['school'], enS: 'Take notes in the notebook.', esS: 'Toma apuntes en el cuaderno.' },
        { w: 'Eraser', es: 'Borrador', id: 'erase', hex: '270f', type: 'object', req: ['school'], enS: 'Fix errors with an eraser.', esS: 'Arregla errores con un borrador.' },
        { w: 'Ruler', es: 'Regla', id: 'ruler', hex: '1f4cf', type: 'object', req: ['school'], enS: 'Measure with a ruler.', esS: 'Mide con una regla.' },
        { w: 'Crayons', es: 'Crayones', id: 'cray', hex: '1f58d', type: 'object', req: ['school'], enS: 'Color the picture.', esS: 'Colorea el dibujo.' },
        { w: 'Glue', es: 'Pegamento', id: 'glue', hex: '1f9f4', type: 'object', req: ['school'], enS: 'Stick the paper with glue.', esS: 'Pega el papel con pegamento.' },
        { w: 'Chalkboard', es: 'Pizarrón', id: 'chalk', hex: '1f3eb', type: 'object', req: ['school'], enS: 'The teacher writes on the board.', esS: 'El maestro escribe en el pizarrón.' },
        { w: 'Computer', es: 'Computadora', id: 'comp', hex: '1f4bb', type: 'object', req: ['school', 'office'], enS: 'I play games on the computer.', esS: 'Juego juegos en la computadora.' },
        { w: 'Microscope', es: 'Microscopio', id: 'micro', hex: '1f52c', type: 'object', req: ['school'], enS: 'Look at small things.', esS: 'Mira cosas pequeñas.' },
        { w: 'Globe', es: 'Globo terráqueo', id: 'globe', hex: '1f30d', type: 'object', req: ['school'], enS: 'The earth is round.', esS: 'La tierra es redonda.' },
        { w: 'Desk', es: 'Pupitre', id: 'desk', hex: '1f3eb', type: 'object', req: ['school'], enS: 'Sit at your desk.', esS: 'Siéntate en tu pupitre.' },
    ],
    'Food & Items': [
        { w: 'Shopping Cart', es: 'Carrito de compras', id: 'cart_item', hex: '1f6d2', type: 'object', req: ['super2'], enS: 'Put the food in the cart.', esS: 'Pon la comida en el carrito.' },
        { w: 'Apple', es: 'Manzana', id: 'f_apple', hex: '1f34e', type: 'object', req: ['super2', 'shop'], enS: 'The red apple is sweet.', esS: 'La manzana roja es dulce.' },
        { w: 'Banana', es: 'Banana', id: 'f_banana', hex: '1f34c', type: 'object', req: ['super2', 'shop'], enS: 'Yellow and long.', esS: 'Amarilla y larga.' },
        { w: 'Grapes', es: 'Uvas', id: 'f_grapes', hex: '1f347', type: 'object', req: ['super2', 'shop'], enS: 'Sweet purple grapes.', esS: 'Dulces uvas moradas.' },
        { w: 'Strawberry', es: 'Fresa', id: 'f_straw', hex: '1f353', type: 'object', req: ['super2', 'shop'], enS: 'Sweet red fruit.', esS: 'Fruta dulce roja.' },
        { w: 'Mango', es: 'Mango', id: 'f_mango', hex: '1f96d', type: 'object', req: ['super2', 'shop'], enS: 'The king of fruits.', esS: 'El rey de las frutas.' },
        { w: 'Carrot', es: 'Zanahoria', id: 'v_carrot', hex: '1f955', type: 'object', req: ['super2', 'shop'], enS: 'Orange and crunchy.', esS: 'Naranja y crujiente.' },
        { w: 'Broccoli', es: 'Brócoli', id: 'v_broc', hex: '1f966', type: 'object', req: ['super2', 'shop'], enS: 'Little green trees.', esS: 'Arbolitos verdes.' },
        { w: 'Corn', es: 'Maíz', id: 'v_corn', hex: '1f33d', type: 'object', req: ['super2', 'shop'], enS: 'Yellow on the cob.', esS: 'Amarillo en la mazorca.' },
        { w: 'Pizza Slice', es: 'Pizza Slice', id: 'food_piz', hex: '1f355', type: 'object', req: ['shop', 'house'], enS: 'Cheesy and hot.', esS: 'Con queso y caliente.' },
        { w: 'Hot Dog', es: 'Perro caliente', id: 'food_hd', hex: '1f32d', type: 'object', req: ['shop', 'park'], enS: 'Sausage in bread.', esS: 'Salchicha en pan.' },
        { w: 'Sandwich', es: 'Sándwich', id: 'food_sand', hex: '1f96a', type: 'object', req: ['shop', 'house'], enS: 'Bread with ham.', esS: 'Pan con jamón.' },
        { w: 'Milk', es: 'Leche', id: 'food_milk', hex: '1f95b', type: 'object', req: ['super2', 'shop'], enS: 'White and healthy.', esS: 'Blanca y saludable.' },
        { w: 'Juice', es: 'Jugo', id: 'food_juice', hex: '1f9c3', type: 'object', req: ['super2', 'shop'], enS: 'Fresh orange juice.', esS: 'Jugo de naranja fresco.' },
        // --- NEW SUPERMARKET ITEMS ---
        { w: 'Bread', es: 'Pan', id: 'f_bread', hex: '1f35e', type: 'object', req: ['bakery2', 'house'], enS: 'Freshly baked bread.', esS: 'Pan recién horneado.' },
        { w: 'Croissant', es: 'Croissant', id: 'f_crois', hex: '1f950', type: 'object', req: ['bakery2', 'cafe'], enS: 'A buttery croissant.', esS: 'Un croissant con mantequilla.' },
        { w: 'Donut', es: 'Dona', id: 'f_donut', hex: '1f369', type: 'object', req: ['bakery2', 'cafe'], enS: 'Sweet glazed donut.', esS: 'Dona dulce glaseada.' },
        { w: 'Cake', es: 'Pastel', id: 'f_cake', hex: '1f382', type: 'object', req: ['bakery2', 'house'], enS: 'Happy Birthday cake!', esS: '¡Pastel de cumpleaños!' },
        { w: 'Cheese', es: 'Queso', id: 'f_cheese', hex: '1f9c0', type: 'object', req: ['super2', 'house'], enS: 'Yellow cheese.', esS: 'Queso amarillo.' },
        { w: 'Ice Cream', es: 'Helado', id: 'f_ice', hex: '1f366', type: 'object', req: ['super2', 'park'], enS: 'Cold ice cream.', esS: 'Helado frío.' },
        { w: 'Yogurt', es: 'Yogur', id: 'f_yog', hex: '1f9c8', type: 'object', req: ['super2', 'house'], enS: 'Healthy yogurt.', esS: 'Yogur saludable.' },
        { w: 'Butter', es: 'Mantequilla', id: 'f_butter', hex: '1f9c8', type: 'object', req: ['super2', 'house'], enS: 'Butter on toast.', esS: 'Mantequilla en el pan.' },
        { w: 'Cereal', es: 'Cereal', id: 'f_cereal', hex: '1f963', type: 'object', req: ['super2', 'house'], enS: 'Cereal with milk.', esS: 'Cereal con leche.' },
        { w: 'Canned Soup', es: 'Sopa enlatada', id: 'f_soup', hex: '1f96b', type: 'object', req: ['super2', 'house'], enS: 'Tomato soup.', esS: 'Sopa de tomate.' },
        { w: 'Pasta', es: 'Pasta', id: 'f_pasta', hex: '1f35d', type: 'object', req: ['super2', 'house'], enS: 'Spaghetti and meatballs.', esS: 'Espagueti con albóndigas.' },
        { w: 'Rice', es: 'Arroz', id: 'f_rice', hex: '1f35a', type: 'object', req: ['super2', 'house'], enS: 'White rice.', esS: 'Arroz blanco.' },
        { w: 'Honey', es: 'Miel', id: 'f_honey', hex: '1f36f', type: 'object', req: ['super2', 'house'], enS: 'Sweet honey from bees.', esS: 'Miel dulce de abejas.' },
        { w: 'Jam', es: 'Mermelada', id: 'f_jam', hex: '1f96b', type: 'object', req: ['super2', 'house'], enS: 'Strawberry jam.', esS: 'Mermelada de fresa.' },
        { w: 'Chocolate', es: 'Chocolate', id: 'f_choc', hex: '1f36b', type: 'object', req: ['super2', 'house'], enS: 'Yummy chocolate bar.', esS: 'Barra de chocolate rica.' },
        { w: 'Egg', es: 'Huevo', id: 'f_egg', hex: '1f95a', type: 'object', req: ['super2', 'house'], enS: 'Crack the egg.', esS: 'Rompe el huevo.' },

        // --- EXPANDED MARKET ITEMS ---
        // FRUITS
        { w: 'Orange', es: 'Naranja', id: 'f_orange', hex: '1f34a', type: 'object', req: ['super2', 'shop'], enS: 'Juicy orange.', esS: 'Naranja jugosa.' },
        { w: 'Pear', es: 'Pera', id: 'f_pear', hex: '1f350', type: 'object', req: ['super2', 'shop'], enS: 'Sweet green pear.', esS: 'Pera dulce y verde.' },
        { w: 'Peach', es: 'Durazno', id: 'f_peach', hex: '1f351', type: 'object', req: ['super2', 'shop'], enS: 'Soft fuzzy peach.', esS: 'Durazno suave.' },
        { w: 'Cherry', es: 'Cereza', id: 'f_cherry', hex: '1f352', type: 'object', req: ['super2', 'shop'], enS: 'Red cherries on top.', esS: 'Cerezas rojas encima.' },
        { w: 'Pineapple', es: 'Piña', id: 'f_pine', hex: '1f34d', type: 'object', req: ['super2', 'shop'], enS: 'Spiky yellow pineapple.', esS: 'Piña amarilla y espinosa.' },
        { w: 'Watermelon', es: 'Sandía', id: 'f_waterm', hex: '1f349', type: 'object', req: ['super2', 'shop'], enS: 'Big green watermelon.', esS: 'Gran sandía verde.' },
        { w: 'Lemon', es: 'Limón', id: 'f_lemon', hex: '1f34b', type: 'object', req: ['super2', 'shop'], enS: 'Sour yellow lemon.', esS: 'Limón amarillo y ácido.' },
        { w: 'Avocado', es: 'Aguacate', id: 'f_avo', hex: '1f951', type: 'object', req: ['super2', 'shop'], enS: 'Green avocado.', esS: 'Aguacate verde.' },
        { w: 'Coconut', es: 'Coco', id: 'f_coco', hex: '1f965', type: 'object', req: ['super2', 'shop'], enS: 'Hard brown coconut.', esS: 'Coco duro y marrón.' },
        { w: 'Kiwi', es: 'Kiwi', id: 'f_kiwi', hex: '1f95d', type: 'object', req: ['super2', 'shop'], enS: 'Fuzzy brown kiwi.', esS: 'Kiwi marrón y peludo.' },

        // VEGETABLES
        { w: 'Lettuce', es: 'Lechuga', id: 'v_lettuce', hex: '1f96c', type: 'object', req: ['super2', 'shop'], enS: 'Green leafy lettuce.', esS: 'Lechuga de hojas verdes.' },
        { w: 'Cucumber', es: 'Pepino', id: 'v_cucum', hex: '1f952', type: 'object', req: ['super2', 'shop'], enS: 'Long green cucumber.', esS: 'Pepino largo y verde.' },
        { w: 'Pepper', es: 'Pimiento', id: 'v_pepper', hex: '1f336', type: 'object', req: ['super2', 'shop'], enS: 'Spicy red pepper.', esS: 'Pimiento rojo picante.' },
        { w: 'Onion', es: 'Cebolla', id: 'v_onion', hex: '1f9c5', type: 'object', req: ['super2', 'shop'], enS: 'Cry with onions.', esS: 'Llora con las cebollas.' },
        { w: 'Garlic', es: 'Ajo', id: 'v_garlic', hex: '1f9c4', type: 'object', req: ['super2', 'shop'], enS: 'Smelly white garlic.', esS: 'Ajo blanco y oloroso.' },
        { w: 'Potato', es: 'Papa', id: 'v_potato', hex: '1f954', type: 'object', req: ['super2', 'shop'], enS: 'Brown potato.', esS: 'Papa café.' },
        { w: 'Tomato', es: 'Tomate', id: 'v_tomato', hex: '1f345', type: 'object', req: ['super2', 'shop'], enS: 'Red juicy tomato.', esS: 'Tomate rojo y jugoso.' },
        { w: 'Eggplant', es: 'Berenjena', id: 'v_eggpl', hex: '1f346', type: 'object', req: ['super2', 'shop'], enS: 'Purple eggplant.', esS: 'Berenjena morada.' },
        { w: 'Peanuts', es: 'Cacahuates', id: 'f_peanut', hex: '1f95c', type: 'object', req: ['super2', 'shop'], enS: 'Crunchy peanuts.', esS: 'Cacahuates crujientes.' },

        // MEAT & PROTEIN REPLACEMENTS (High Protein Veggie)
        { w: 'Tofu', es: 'Tofu', id: 'm_tofu', hex: '1f9c8', type: 'object', req: ['super2', 'shop'], enS: 'Soy bean tofu.', esS: 'Tofu de soya.' },
        { w: 'Hummus', es: 'Hummus', id: 'm_hummus', hex: '1f9c6', type: 'object', req: ['super2', 'shop'], enS: 'Chickpea dip.', esS: 'Dip de garbanzo.' },
        { w: 'Almonds', es: 'Almendras', id: 'm_almond', hex: '1f95c', type: 'object', req: ['super2', 'shop'], enS: 'Crunchy almonds.', esS: 'Almendras crujientes.' },
        { w: 'Lentils', es: 'Lentejas', id: 'm_lentil', hex: '1f96b', type: 'object', req: ['super2', 'shop'], enS: 'Bag of lentils.', esS: 'Bolsa de lentejas.' },

        // BAKERY & BREAKFAST
        { w: 'Pancake', es: 'Panqueque', id: 'b_pan', hex: '1f95e', type: 'object', req: ['bakery2', 'cafe'], enS: 'Stack of pancakes.', esS: 'Pila de panqueques.' },
        { w: 'Waffle', es: 'Waffle', id: 'b_waf', hex: '1f9c7', type: 'object', req: ['bakery2', 'cafe'], enS: 'Square waffle.', esS: 'Waffle cuadrado.' },
        { w: 'Bagel', es: 'Bagel', id: 'b_bagel', hex: '1f96f', type: 'object', req: ['bakery2', 'shop'], enS: 'Round bagel.', esS: 'Bagel redondo.' },
        { w: 'Pie', es: 'Pastel de frutas', id: 'b_pie', hex: '1f967', type: 'object', req: ['bakery2', 'house'], enS: 'Apple pie.', esS: 'Pastel de manzana.' },
        { w: 'Pretzel', es: 'Pretzel', id: 'b_pretzel', hex: '1f968', type: 'object', req: ['bakery2', 'shop'], enS: 'Salty pretzel.', esS: 'Pretzel salado.' },
        { w: 'Muffin', es: 'Muffin', id: 'b_muf', hex: '1f9c1', type: 'object', req: ['bakery2', 'cafe'], enS: 'Blueberry muffin.', esS: 'Muffin de arándanos.' },
        { w: 'Tart', es: 'Tarta', id: 'b_tart', hex: '1f967', type: 'object', req: ['bakery2', 'cafe'], enS: 'Fruit tart.', esS: 'Tarta de frutas.' },

        // PANTRY & SNACKS
        { w: 'Soda', es: 'Refresco', id: 'p_soda', hex: '1f964', type: 'object', req: ['super2', 'shop'], enS: 'Fizzy soda drink.', esS: 'Refresco con gas.' },
        { w: 'Water Bottle', es: 'Agua', id: 'p_water', hex: '1f95f', type: 'object', req: ['super2', 'shop'], enS: 'Drink water daily.', esS: 'Bebe agua a diario.' },
        { w: 'Popcorn', es: 'Palomitas', id: 'p_pop', hex: '1f37f', type: 'object', req: ['super2', 'shop'], enS: 'Popcorn for movies.', esS: 'Palomitas para cine.' },
        { w: 'Cookie', es: 'Galleta', id: 'p_cookie', hex: '1f36a', type: 'object', req: ['super2', 'shop'], enS: 'Choc chip cookie.', esS: 'Galleta con chispas.' },
        { w: 'Candy', es: 'Dulce', id: 'p_candy', hex: '1f36c', type: 'object', req: ['super2', 'shop'], enS: 'Sweet sugary candy.', esS: 'Dulce azucarado.' },
        { w: 'Lollipop', es: 'Paleta', id: 'p_lolly', hex: '1f36d', type: 'object', req: ['super2', 'shop'], enS: 'Lick the lollipop.', esS: 'Lame la paleta.' },
        { w: 'Fries', es: 'Papas fritas', id: 'p_fries', hex: '1f35f', type: 'object', req: ['super2', 'shop'], enS: 'Salty french fries.', esS: 'Papas a la francesa saladas.' },
        { w: 'Veggie Burger', es: 'Hamburguesa Veg', id: 'p_vburg', hex: '1f354', type: 'object', req: ['super2', 'shop'], enS: 'Plant based burger.', esS: 'Hamburguesa de plantas.' },
        { w: 'Veggie Taco', es: 'Taco Vegetariano', id: 'p_vtaco', hex: '1f32e', type: 'object', req: ['super2', 'shop'], enS: 'Bean taco.', esS: 'Taco de frijoles.' },
        { w: 'Salt', es: 'Sal', id: 'p_salt', hex: '1f9c2', type: 'object', req: ['super2', 'house'], enS: 'Add salt to food.', esS: 'Ponle sal a la comida.' },
        { w: 'Sugar', es: 'Azúcar', id: 'p_sugar', hex: '1f9c2', type: 'object', req: ['super2', 'house'], enS: 'Sweet white sugar.', esS: 'Azúcar blanca dulce.' },
        { w: 'Flour', es: 'Harina', id: 'p_flour', hex: '1f961', type: 'object', req: ['super2', 'house'], enS: 'Bake with flour.', esS: 'Hornea con harina.' },
        { w: 'Oil', es: 'Aceite', id: 'p_oil', hex: '1f9ea', type: 'object', req: ['super2', 'house'], enS: 'Cooking oil.', esS: 'Aceite para cocinar.' },
        { w: 'Tea', es: 'Té', id: 'p_tea', hex: '1f375', type: 'object', req: ['super2', 'cafe'], enS: 'Hot green tea.', esS: 'Té verde caliente.' },
        { w: 'Coffee', es: 'Café', id: 'p_coffee', hex: '2615', type: 'object', req: ['super2', 'cafe'], enS: 'Hot black coffee.', esS: 'Café negro caliente.' },

        // --- HYGIENE & BEAUTY ---
        { w: 'Shampoo', es: 'Champú', id: 'h_sham', hex: '1f9f4', type: 'object', req: ['super2', 'pharmacy'], enS: 'Wash your hair.', esS: 'Lava tu cabello.' },
        { w: 'Conditioner', es: 'Acondicionador', id: 'h_cond', hex: '1f9f4', type: 'object', req: ['super2', 'pharmacy'], enS: 'Soft silky hair.', esS: 'Cabello suave y sedoso.' },
        { w: 'Soap', es: 'Jabón', id: 'h_soap', hex: '1f9fc', type: 'object', req: ['super2', 'pharmacy'], enS: 'Clean your hands.', esS: 'Limpia tus manos.' },
        { w: 'Toothbrush', es: 'Cepillo de dientes', id: 'h_brush', hex: '1fae5', type: 'object', req: ['super2', 'pharmacy'], enS: 'Brush your teeth.', esS: 'Cepilla tus dientes.' },
        { w: 'Toothpaste', es: 'Pasta dental', id: 'h_paste', hex: '1f9b7', type: 'object', req: ['super2', 'pharmacy'], enS: 'Minty fresh breath.', esS: 'Aliento fresco a menta.' },
        { w: 'Deodorant', es: 'Desodorante', id: 'h_deo', hex: '1f9ca', type: 'object', req: ['super2', 'pharmacy'], enS: 'Smell good all day.', esS: 'Huele bien todo el día.' },
        { w: 'Hair Dye', es: 'Tinte de pelo', id: 'h_dye', hex: '1f487', type: 'object', req: ['super2', 'pharmacy'], enS: 'Change hair color.', esS: 'Cambia el color del cabello.' },
        { w: 'Toilet Paper', es: 'Papel higiénico', id: 'h_tp', hex: '1f9fb', type: 'object', req: ['super2', 'pharmacy'], enS: 'Bathroom tissue.', esS: 'Papel de baño.' },
        { w: 'Tissues', es: 'Pañuelos', id: 'h_tiss', hex: '1f9fb', type: 'object', req: ['super2', 'pharmacy'], enS: 'For your nose.', esS: 'Para tu nariz.' },
        { w: 'Sunscreen', es: 'Bloqueador solar', id: 'h_sun', hex: '1f9f4', type: 'object', req: ['super2', 'pharmacy'], enS: 'Protect your skin.', esS: 'Protege tu piel.' },
        { w: 'Perfume', es: 'Perfume', id: 'h_perf', hex: '1f391', type: 'object', req: ['super2', 'pharmacy'], enS: 'Lovely scent.', esS: 'Aroma encantador.' },
        { w: 'Lipstick', es: 'Labial', id: 'h_lip', hex: '1f484', type: 'object', req: ['super2', 'pharmacy'], enS: 'Red lips.', esS: 'Labios rojos.' },
        { w: 'Nail Polish', es: 'Esmalte', id: 'h_nail', hex: '1f485', type: 'object', req: ['super2', 'pharmacy'], enS: 'Colorful nails.', esS: 'Uñas coloridas.' },
        { w: 'Razor', es: 'Rastrillo', id: 'h_razor', hex: '1fa92', type: 'object', req: ['super2', 'pharmacy'], enS: 'Shave beard.', esS: 'Afeita la barba.' },
        { w: 'Comb', es: 'Peine', id: 'h_comb', hex: '1f487', type: 'object', req: ['super2', 'pharmacy'], enS: 'Style your hair.', esS: 'Peina tu cabello.' },
        { w: 'Lotion', es: 'Crema', id: 'h_lotion', hex: '1f9f4', type: 'object', req: ['super2', 'pharmacy'], enS: 'Soft skin.', esS: 'Piel suave.' },
        { w: 'Bandage', es: 'Curita', id: 'h_band', hex: '1fa79', type: 'object', req: ['super2', 'pharmacy'], enS: 'Fix a boo-boo.', esS: 'Cura una herida.' },
        { w: 'Vitamins', es: 'Vitaminas', id: 'h_vit', hex: '1f48a', type: 'object', req: ['super2', 'pharmacy'], enS: 'Stay healthy.', esS: 'Mantente saludable.' },
        { w: 'Diapers', es: 'Pañales', id: 'h_diap', hex: '1f476', type: 'object', req: ['super2', 'pharmacy'], enS: 'For the baby.', esS: 'Para el bebé.' },

        // --- HOUSEHOLD & CLEANING ---
        { w: 'Detergent', es: 'Detergente', id: 'cl_det', hex: '1f9f4', type: 'object', req: ['super2', 'house'], enS: 'Clean clothes.', esS: 'Ropa limpia.' },
        { w: 'Sponge', es: 'Esponja', id: 'cl_spg', hex: '1f9fd', type: 'object', req: ['super2', 'house'], enS: 'Wash dishes.', esS: 'Lava los platos.' },
        { w: 'Broom', es: 'Escoba', id: 'cl_broom', hex: '1f9f9', type: 'object', req: ['super2', 'house'], enS: 'Sweep the floor.', esS: 'Barre el piso.' },
        { w: 'Bucket', es: 'Cubeta', id: 'cl_buck', hex: '1f5d1', type: 'object', req: ['super2', 'house'], enS: 'Hold water.', esS: 'Sostén agua.' },
        { w: 'Trash Bags', es: 'Bolsas de basura', id: 'cl_bag', hex: '1f5d1', type: 'object', req: ['super2', 'house'], enS: 'Clean up trash.', esS: 'Recoge la basura.' },
        { w: 'Batteries', es: 'Baterías', id: 'cl_bat', hex: '1f50b', type: 'object', req: ['super2', 'house'], enS: 'Power for toys.', esS: 'Energía para juguetes.' },
        { w: 'Light Bulb', es: 'Bombilla', id: 'cl_bulb', hex: '1f4a1', type: 'object', req: ['super2', 'house'], enS: 'Bright light.', esS: 'Luz brillante.' },

        // --- PETS ---
        { w: 'Dog Food', es: 'Comida de perro', id: 'pet_dog', hex: '1f9b4', type: 'object', req: ['super2', 'house'], enS: 'Yummy for dogs.', esS: 'Rico para perros.' },
        { w: 'Cat Food', es: 'Comida de gato', id: 'pet_cat', hex: '1f96b', type: 'object', req: ['super2', 'house'], enS: 'Healthy canned food for cats.', esS: 'Comida enlatada para gatos.' },

        // --- MORE PANTRY ---
        { w: 'Ketchup', es: 'Salsa de tomate', id: 'p_ketch', hex: '1f345', type: 'object', req: ['super2', 'shop'], enS: 'Red sauce.', esS: 'Salsa roja.' },
        { w: 'Mustard', es: 'Mostaza', id: 'p_must', hex: '1f32d', type: 'object', req: ['super2', 'shop'], enS: 'Yellow sauce.', esS: 'Salsa amarilla.' },
        { w: 'Mayonnaise', es: 'Mayonesa', id: 'p_mayo', hex: '1f95a', type: 'object', req: ['super2', 'shop'], enS: 'Creamy mayo.', esS: 'Mayonesa cremosa.' },
        { w: 'Spaghetti', es: 'Espagueti', id: 'p_spag', hex: '1f35d', type: 'object', req: ['super2', 'shop'], enS: 'Long pasta.', esS: 'Pasta larga.' },
        { w: 'Rice Bag', es: 'Bolsa de arroz', id: 'p_riceb', hex: '1f35a', type: 'object', req: ['super2', 'shop'], enS: 'Big bag of rice.', esS: 'Bolsa grande de arroz.' },
        { w: 'Beans', es: 'Frijoles', id: 'p_beans', hex: '1f96b', type: 'object', req: ['super2', 'shop'], enS: 'Canned beans.', esS: 'Frijoles enlatados.' },
        { w: 'Peanut Butter', es: 'Mantequilla de maní', id: 'p_pb', hex: '1fac0', type: 'object', req: ['super2', 'shop'], enS: 'Nutty spread.', esS: 'Untable de nuez.' },
        { w: 'Hot Sauce', es: 'Salsa picante', id: 'p_hot', hex: '1f336', type: 'object', req: ['super2', 'shop'], enS: 'Very spicy!', esS: '¡Muy picante!' },
        { w: 'Vanilla', es: 'Vainilla', id: 'p_van', hex: '1f33c', type: 'object', req: ['super2', 'house'], enS: 'For baking.', esS: 'Para hornear.' },
        { w: 'Olive Oil', es: 'Aceite de oliva', id: 'p_ooil', hex: '1fad2', type: 'object', req: ['super2', 'shop'], enS: 'Healthy oil.', esS: 'Aceite saludable.' },
        { w: 'Vinegar', es: 'Vinagre', id: 'p_vin', hex: '1f9c2', type: 'object', req: ['super2', 'shop'], enS: 'Sour vinegar.', esS: 'Vinagre ácido.' },
        { w: 'Oats', es: 'Avena', id: 'p_oats', hex: '1f33e', type: 'object', req: ['super2', 'shop'], enS: 'Healthy oats.', esS: 'Avena saludable.' },

        // --- MORE SNACKS & SWEETS ---
        { w: 'Gum', es: 'Chicle', id: 'sn_gum', hex: '1f445', type: 'object', req: ['super2', 'shop'], enS: 'Chewy bubblegum.', esS: 'Chicle masticable.' },
        { w: 'Chocolate Bar', es: 'Barra de chocolate', id: 'sn_bar', hex: '1f36b', type: 'object', req: ['super2', 'shop'], enS: 'Sweet treat.', esS: 'Dulce regalo.' },
        { w: 'Mints', es: 'Mentas', id: 'sn_mint', hex: '1f36c', type: 'object', req: ['super2', 'shop'], enS: 'Fresh breath.', esS: 'Aliento fresco.' },
        { w: 'Pudding', es: 'Pudín', id: 'sn_pud', hex: '1f36e', type: 'object', req: ['super2', 'house'], enS: 'Creamy dessert.', esS: 'Postre cremoso.' },
        { w: 'Chips', es: 'Papas fritas', id: 'sn_chips', hex: '1f35f', type: 'object', req: ['super2', 'shop'], enS: 'Crunchy chips.', esS: 'Papas crujientes.' },
        { w: 'Gummy Bears', es: 'Ositos de goma', id: 'sn_gummy', hex: '1f43b', type: 'object', req: ['super2', 'shop'], enS: 'Chewy bears.', esS: 'Ositos masticables.' },

        // --- MORE DRINKS ---
        { w: 'Orange Juice', es: 'Jugo de naranja', id: 'd_oj', hex: '1f9c3', type: 'object', req: ['super2', 'shop'], enS: 'Fresh OJ.', esS: 'Jugo de naranja fresco.' },
        { w: 'Apple Juice', es: 'Jugo de manzana', id: 'd_aj', hex: '1f9c3', type: 'object', req: ['super2', 'shop'], enS: 'Sweet apple juice.', esS: 'Jugo de manzana dulce.' },
        { w: 'Lemonade', es: 'Limonada', id: 'd_lem', hex: '1f964', type: 'object', req: ['super2', 'shop'], enS: 'Cold lemonade.', esS: 'Limonada fría.' },
        { w: 'Iced Tea', es: 'Té helado', id: 'd_tea', hex: '1f9cb', type: 'object', req: ['super2', 'shop'], enS: 'Refreshing tea.', esS: 'Té refrescante.' },
        { w: 'Hot Cocoa', es: 'Chocolate caliente', id: 'd_cocoa', hex: '2615', type: 'object', req: ['super2', 'cafe'], enS: 'Warm chocolate.', esS: 'Chocolate caliente.' },
        { w: 'Smoothie', es: 'Batido', id: 'd_smoothie', hex: '1f964', type: 'object', req: ['super2', 'cafe'], enS: 'Fruit smoothie.', esS: 'Batido de frutas.' },

        // --- FROZEN ---
        { w: 'Ice Cream Tub', es: 'Bote de helado', id: 'fr_tub', hex: '1f366', type: 'object', req: ['super2', 'house'], enS: 'Vanilla flavor.', esS: 'Sabor vainilla.' },
        { w: 'Popsicle', es: 'Paleta de hielo', id: 'fr_pop', hex: '1f368', type: 'object', req: ['super2', 'park'], enS: 'Cold fruity treat.', esS: 'Dulce frutal frío.' },
        { w: 'Frozen Pizza', es: 'Pizza congelada', id: 'fr_piz', hex: '1f355', type: 'object', req: ['super2', 'house'], enS: 'Bake at home.', esS: 'Hornea en casa.' },
        { w: 'Frozen Peas', es: 'Chícharos congelados', id: 'fr_pea', hex: '1f9ec', type: 'object', req: ['super2', 'house'], enS: 'Ice cold veggies.', esS: 'Verduras heladas.' },
        { w: 'Frozen Berries', es: 'Bayas congeladas', id: 'fr_ber', hex: '1f353', type: 'object', req: ['super2', 'house'], enS: 'For smoothies.', esS: 'Para batidos.' },

        // --- KITCHENWARE ---
        { w: 'Plate', es: 'Plato', id: 'k_plate', hex: '1f37d', type: 'object', req: ['super2', 'house'], enS: 'Dinner plate.', esS: 'Plato para cenar.' },
        { w: 'Bowl', es: 'Tazón', id: 'k_bowl', hex: '1f963', type: 'object', req: ['super2', 'house'], enS: 'Soup bowl.', esS: 'Tazón para sopa.' },
        { w: 'Cup', es: 'Taza', id: 'k_cup', hex: '1f964', type: 'object', req: ['super2', 'house'], enS: 'Drink from a cup.', esS: 'Bebe de una taza.' },
        { w: 'Fork', es: 'Tenedor', id: 'k_fork', hex: '1f374', type: 'object', req: ['super2', 'house'], enS: 'Eat with a fork.', esS: 'Come con un tenedor.' },
        { w: 'Spoon', es: 'Cuchara', id: 'k_spoon', hex: '1f944', type: 'object', req: ['super2', 'house'], enS: 'Soup spoon.', esS: 'Cuchara para sopa.' },
        { w: 'Knife', es: 'Cuchillo', id: 'k_knife', hex: '1f52a', type: 'object', req: ['super2', 'house'], enS: 'Butter knife.', esS: 'Cuchillo para mantequilla.' },
        { w: 'Frying Pan', es: 'Sartén', id: 'k_pan', hex: '1f373', type: 'object', req: ['super2', 'house'], enS: 'Fry an egg.', esS: 'Fríe un huevo.' },
        { w: 'Pot', es: 'Olla', id: 'k_pot', hex: '1f372', type: 'object', req: ['super2', 'house'], enS: 'Boil water.', esS: 'Hierve agua.' },
        { w: 'Spatula', es: 'Espátula', id: 'k_spat', hex: '1f373', type: 'object', req: ['super2', 'house'], enS: 'Flip pancakes.', esS: 'Voltea los panqueques.' },

        // --- STATIONERY ---
        { w: 'Notebook', es: 'Cuaderno', id: 'st_note', hex: '1f4d3', type: 'object', req: ['super2', 'school'], enS: 'Write notes.', esS: 'Escribe notas.' },
        { w: 'Pen', es: 'Bolígrafo', id: 'st_pen', hex: '1f58a', type: 'object', req: ['super2', 'school'], enS: 'Blue ink pen.', esS: 'Bolígrafo de tinta azul.' },
        { w: 'Pencil', es: 'Lápiz', id: 'st_pencil', hex: '270f', type: 'object', req: ['super2', 'school'], enS: 'Sharpen the pencil.', esS: 'Saca punta al lápiz.' },
        { w: 'Eraser', es: 'Borrador', id: 'st_erase', hex: '1f9f1', type: 'object', req: ['super2', 'school'], enS: 'Erase mistakes.', esS: 'Borra errores.' },
        { w: 'Glue', es: 'Pegamento', id: 'st_glue', hex: '1f9ea', type: 'object', req: ['super2', 'school'], enS: 'Stick paper.', esS: 'Pega papel.' },
        { w: 'Scissors', es: 'Tijeras', id: 'st_scis', hex: '2702', type: 'object', req: ['super2', 'school'], enS: 'Cut paper.', esS: 'Corta papel.' },
        { w: 'Ruler', es: 'Regla', id: 'st_rule', hex: '1f4cf', type: 'object', req: ['super2', 'school'], enS: 'Measure lines.', esS: 'Mide líneas.' },
        { w: 'Crayons', es: 'Crayones', id: 'st_cray', hex: '1f58d', type: 'object', req: ['super2', 'school'], enS: 'Color the picture.', esS: 'Colorea el dibujo.' },
        { w: 'Backpack', es: 'Mochila', id: 'st_bag', hex: '1f392', type: 'object', req: ['super2', 'school'], enS: 'Pack your books.', esS: 'Empaca tus libros.' },
    ],
    'Nature': [
        { w: 'Lake', es: 'Lago', id: 'water', hex: '1f30a', type: 'base', enS: 'The lake is clear.', esS: 'El lago está claro.' },
        { w: 'Park', es: 'Parque', id: 'park', hex: '1f3de', type: 'base', enS: 'The grass is green.', esS: 'El césped es verde.' },
        { w: 'Forest', es: 'Bosque', id: 'tree', hex: '1f333', type: 'object', req: ['grass', 'park'], enS: 'Trees grow tall.', esS: 'Los árboles crecen altos.' },
        { w: 'Mountain', es: 'Montaña', id: 'mountain', hex: '26f0', type: 'object', req: ['grass'], enS: 'The peak is white.', esS: 'La cima es blanca.' },
        { w: 'Volcano', es: 'Volcán', id: 'volcano', hex: '1f30b', type: 'object', req: ['grass'], enS: 'Lava flows down.', esS: 'La lava fluye hacia abajo.' },
        { w: 'Beach', es: 'Playa', id: 'sand', hex: '1f3d6', type: 'base', enS: 'Play with the sand.', esS: 'Juega con la arena.' },
        { w: 'Cactus', es: 'Cactus', id: 'cactus', hex: '1f335', type: 'object', req: ['sand'], enS: 'Cactus lives in the desert.', esS: 'El cactus vive en el desierto.', ttsS: 'Cactus livs in the desert.' },
        { w: 'Palm Tree', es: 'Palmera', id: 'palm', hex: '1f334', type: 'object', req: ['sand', 'grass'], enS: 'Palm trees on the beach.', esS: 'Palmeras en la playa.' },
        { w: 'Sunflower', es: 'Girasol', id: 'sunflower', hex: '1f33b', type: 'object', req: ['park', 'grass'], enS: 'Sunflowers are yellow.', esS: 'Los girasoles son amarillos.' },
        { w: 'Rose', es: 'Rosa', id: 'rose', hex: '1f339', type: 'object', req: ['park', 'grass'], enS: 'The red rose is pretty.', esS: 'La rosa roja es bonita.' },
        { w: 'Mushroom', es: 'Hongo', id: 'mushroom', hex: '1f344', type: 'object', req: ['park', 'grass'], enS: 'Mushrooms grow in the shade.', esS: 'Los hongos crecen en la sombra.' },
        { w: 'Evergreen', es: 'Pino', id: 'pine', hex: '1f332', type: 'object', req: ['mountain', 'grass'], enS: 'A Christmas tree is a pine.', esS: 'Un árbol de navidad es un pino.' },
        { w: 'Island', es: 'Isla', id: 'island', hex: '1f3dd', type: 'base', enS: 'An island in the sea.', esS: 'Una isla en el mar.' },
        { w: 'Snowy Ground', es: 'Nieve', id: 'snow', hex: '2744', type: 'base', enS: 'The floor is white.', esS: 'El suelo está blanco.' },
        { w: 'Field', es: 'Campo', id: 'field', hex: '1f33e', type: 'base', enS: 'Wheat grows in the field.', esS: 'El trigo crece en el campo.' },
        { w: 'Waterfall', es: 'Cascada', id: 'waterf', hex: '1f30a', type: 'object', req: ['mountain', 'grass'], enS: 'Water falls from heights.', esS: 'El agua cae desde las alturas.' },
        { w: 'Rainbow', es: 'Arcoíris', id: 'rainbow', hex: '1f308', type: 'object', req: ['sky', 'park'], enS: 'The colors are beautiful.', esS: 'Los colores son hermosos.' },
        { w: 'Cave', es: 'Cueva', id: 'cave', hex: '1f573', type: 'object', req: ['mountain'], enS: 'The cave is dark.', esS: 'La cueva está oscura.' },
        { w: 'Campfire', es: 'Fogata', id: 'fire', hex: '1f525', type: 'object', req: ['grass', 'park'], enS: 'Cook over the fire.', esS: 'Cocina sobre el fuego.' },
        { w: 'Swamp', es: 'Pantano', id: 'swamp', hex: '1f3de', type: 'base', enS: 'The swamp is muddy.', esS: 'El pantano está lodoso.' },
        { w: 'Desert', es: 'Desierto', id: 'desert', hex: '1f3dc', type: 'base', enS: 'The desert is very dry.', esS: 'El desierto es muy seco.' },
        { w: 'Winter', es: 'Invierno', id: 's_winter', hex: '2744', type: 'object', req: ['snow'], enS: 'It snows in winter.', esS: 'Nieva en invierno.' },
        { w: 'Summer', es: 'Verano', id: 's_summer', hex: '2600', type: 'object', req: ['sand', 'park'], enS: 'It is hot in summer.', esS: 'Hace calor en verano.' },
        { w: 'Autumn', es: 'Otoño', id: 's_autumn', hex: '1f342', type: 'object', req: ['park', 'forest'], enS: 'Leaves fall in autumn.', esS: 'Las hojas caen en otoño.' },
        { w: 'Spring', es: 'Primavera', id: 's_spring', hex: '1f338', type: 'object', req: ['park', 'flower'], enS: 'Flowers bloom in spring.', esS: 'Las flores brotan en primavera.' },
    ],
    'Vehicles': [
        { w: 'Car', es: 'Carro', id: 'car', hex: '1f697', type: 'object', req: ['road', 'parking'], enS: 'The red car is fast.', esS: 'El carro rojo es rápido.' },
        { w: 'Bus', es: 'Autobús', id: 'bus', hex: '1f68c', type: 'object', req: ['road'], enS: 'The yellow bus stops.', esS: 'El autobús amarillo para.', tts: 'A bus' },
        { w: 'Truck', es: 'Camión', id: 'truck', hex: '1f69a', type: 'object', req: ['road'], enS: 'The big truck carries boxes.', esS: 'El camión grande lleva cajas.' },
        { w: 'Police Car', es: 'Patrulla', id: 'police', hex: '1f693', type: 'object', req: ['road'], enS: 'The police help people.', esS: 'La policía ayuda a la gente.' },
        { w: 'Ambulance', es: 'Ambulancia', id: 'amb', hex: '1f691', type: 'object', req: ['road'], enS: 'The ambulance goes fast.', esS: 'La ambulancia va rápido.' },
        { w: 'Fire Truck', es: 'Camión de bomberos', id: 'fire', hex: '1f692', type: 'object', req: ['road'], enS: 'Put out the fire.', esS: 'Apaga el fuego.' },
        { w: 'Taxi', es: 'Taxi', id: 'taxi', hex: '1f695', type: 'object', req: ['road'], enS: 'Call a yellow taxi.', esS: 'Llama a un taxi amarillo.' },
        { w: 'Bicycle', es: 'Bicicleta', id: 'bike', hex: '1f6b2', type: 'object', req: ['sidewalk', 'park'], enS: 'Ride your bike.', esS: 'Monta tu bicicleta.' },
        { w: 'Motorcycle', es: 'Motocicleta', id: 'moto', hex: '1f3cd', type: 'object', req: ['road'], enS: 'The motorcycle is loud.', esS: 'La motocicleta es ruidosa.' },
        { w: 'Train', es: 'Tren', id: 'train', hex: '1f682', type: 'object', req: ['road'], enS: 'Choo choo says the train.', esS: 'Chu chu dice el tren.' },
        { w: 'Tram', es: 'Tranvía', id: 'tram', hex: '1f68b', type: 'object', req: ['road'], enS: 'The tram runs on rails.', esS: 'El tranvía corre sobre rieles.' },
        { w: 'Helicopter', es: 'Helicóptero', id: 'heli', hex: '1f681', type: 'object', req: ['office', 'grass'], enS: 'The helicopter flies high.', esS: 'El helicóptero vuela alto.' },
        { w: 'Airplane', es: 'Avión', id: 'plane', hex: '2708', type: 'object', req: ['grass'], enS: 'The jet is in the sky.', esS: 'El jet está en el cielo.' },
        { w: 'Rocket', es: 'Cohete', id: 'rocket', hex: '1f680', type: 'object', req: ['grass'], enS: 'Fly to space.', esS: 'Vuela al espacio.' },
        { w: 'Ship', es: 'Barco', id: 'ship', hex: '1f6a2', type: 'object', req: ['water'], enS: 'The ship is on the ocean.', esS: 'El barco está en el océano.' },
        { w: 'Speedboat', es: 'Lancha', id: 'boat', hex: '1f6a4', type: 'object', req: ['water'], enS: 'The boat goes fast.', esS: 'La lancha va rápido.' },
        { w: 'Submarine', es: 'Submarino', id: 'sub', hex: '1f6a2', type: 'object', req: ['water'], enS: 'It goes under water.', esS: 'Va bajo el agua.' },
        { w: 'Scooter', es: 'Scooter', id: 'scooter', hex: '1f6f4', type: 'object', req: ['sidewalk', 'park'], enS: 'Push with your foot.', esS: 'Empuja con tu pie.' },
        { w: 'Skateboard', es: 'Patineta', id: 'skate', hex: '1f6f9', type: 'object', req: ['park', 'sidewalk'], enS: 'Do a trick on the skate.', esS: 'Haz un truco en la patineta.' },
        { w: 'Tractor', es: 'Tractor', id: 'tractor', hex: '1f69c', type: 'object', req: ['grass'], enS: 'Farmers use the tractor.', esS: 'Los agricultores usan el tractor.' },
        { w: 'Dump Truck', es: 'Camión de basura', id: 'dump', hex: '1f69b', type: 'object', req: ['road'], enS: 'Pick up the trash.', esS: 'Recoge la basura.' },
        { w: 'Forklift', es: 'Montacargas', id: 'fork', hex: '1f6dc', type: 'object', req: ['factory'], enS: 'Lift heavy boxes.', esS: 'Levanta cajas pesadas.' },
        { w: 'Canoe', es: 'Canoa', id: 'canoe', hex: '1f6f6', type: 'object', req: ['water'], enS: 'Paddle on the river.', esS: 'Rema en el río.' },
        { w: 'Scooter', es: 'Patineta eléctrica', id: 'scoot', hex: '1f6f4', type: 'object', req: ['sidewalk'], enS: 'Ride fast safely.', esS: 'Viaja rápido con seguridad.' },
        { w: 'Rowboat', es: 'Bote de remos', id: 'rowb', hex: '1f6a3', type: 'object', req: ['water'], enS: 'Row your boat.', esS: 'Rema tu bote.' },
        { w: 'Ferry', es: 'Ferry', id: 'ferry', hex: '26f4', type: 'object', req: ['water'], enS: 'The ferry goes to the island.', esS: 'El ferry va a la isla.' },
    ],
    'Animals': [
        { w: 'Dog', es: 'Perro', id: 'dog', hex: '1f415', type: 'object', req: ['park', 'grass'], enS: 'The dog barks loud.', esS: 'El perro ladra fuerte.' },
        { w: 'Cat', es: 'Gato', id: 'cat', hex: '1f408', type: 'object', req: ['house', 'sidewalk'], enS: 'The cat sleeps all day.', esS: 'El gato duerme todo el día.' },
        { w: 'Bird', es: 'Pájaro', id: 'bird', hex: '1f426', type: 'object', req: ['tree', 'park'], enS: 'The bird sings a song.', esS: 'El pájaro canta una canción.' },
        { w: 'Rabbit', es: 'Conejo', id: 'bunny', hex: '1f407', type: 'object', req: ['grass', 'park'], enS: 'The rabbit hops away.', esS: 'El conejo salta lejos.' },
        { w: 'Duck', es: 'Pato', id: 'duck', hex: '1f986', type: 'object', req: ['water'], enS: 'The duck swims in the lake.', esS: 'El pato nada en el lago.' },
        { w: 'Frog', es: 'Rana', id: 'frog', hex: '1f438', type: 'object', req: ['water', 'park'], enS: 'The green frog jumps.', esS: 'La rana verde salta.' },
        { w: 'Butterfly', es: 'Mariposa', id: 'fly', hex: '1f98b', type: 'object', req: ['park', 'flower'], enS: 'The butterfly has wings.', esS: 'La mariposa tiene alas.' },
        { w: 'Horse', es: 'Caballo', id: 'horse', hex: '1f40e', type: 'object', req: ['grass', 'field'], enS: 'The horse runs fast.', esS: 'El caballo corre rápido.' },
        { w: 'Cow', es: 'Vaca', id: 'cow', hex: '1f404', type: 'object', req: ['grass', 'field'], enS: 'The cow says moo.', esS: 'La vaca dice mu.' },
        { w: 'Sheep', es: 'Oveja', id: 'sheep', hex: '1f411', type: 'object', req: ['grass', 'field'], enS: 'The wool is soft.', esS: 'La lana es suave.' },
        { w: 'Squirrel', es: 'Ardilla', id: 'sq', hex: '1f43f', type: 'object', req: ['tree', 'park'], enS: 'The squirrel eats nuts.', esS: 'La ardilla come nueces.' },
        { w: 'Fish', es: 'Pez', id: 'fish', hex: '1f41f', type: 'object', req: ['water'], enS: 'The fish swims.', esS: 'El pez nada.' },
        { w: 'Bee', es: 'Abeja', id: 'bee', hex: '1f41d', type: 'object', req: ['flower', 'park'], enS: 'The bee makes honey.', esS: 'La abeja hace miel.' },
        { w: 'Elephant', es: 'Elefante', id: 'ele', hex: '1f418', type: 'object', req: ['grass'], enS: 'The elephant is giant.', esS: 'El elefante es gigante.' },
        { w: 'Lion', es: 'León', id: 'lion', hex: '1f981', type: 'object', req: ['grass'], enS: 'The lion roars.', esS: 'El león ruge.' },
        { w: 'Tiger', es: 'Tigre', id: 'tiger', hex: '1f405', type: 'object', req: ['grass', 'forest'], enS: 'The tiger has stripes.', esS: 'El tigre tiene rayas.' },
        { w: 'Monkey', es: 'Mono', id: 'monkey', hex: '1f412', type: 'object', req: ['tree'], enS: 'The monkey climbs trees.', esS: 'El mono trepa árboles.' },
        { w: 'Zebra', es: 'Cebra', id: 'zebra_a', hex: '1f993', type: 'object', req: ['grass'], enS: 'Black and white stripes.', esS: 'Rayas blancas y negras.' },
        { w: 'Giraffe', es: 'Jirafa', id: 'giraffe', hex: '1f992', type: 'object', req: ['grass'], enS: 'Long neck to eat leaves.', esS: 'Cuello largo para comer hojas.' },
        { w: 'Crocodile', es: 'Cocodrilo', id: 'croc', hex: '1f40a', type: 'object', req: ['water'], enS: 'Sharp teeth in the river.', esS: 'Dientes afilados en el río.' },
        { w: 'Penguin', es: 'Pingüino', id: 'peng', hex: '1f427', type: 'object', req: ['snow'], enS: 'I live in the cold.', esS: 'Vivo en el frío.' },
        { w: 'Wolf', es: 'Lobo', id: 'wolf', hex: '1f43a', type: 'object', req: ['forest', 'mountain'], enS: 'The wolf howls.', esS: 'El lobo aúlla.' },
        { w: 'Bear', es: 'Oso', id: 'bear', hex: '1f43b', type: 'object', req: ['forest', 'mountain'], enS: 'A big brown bear.', esS: 'Un gran oso café.' },
        { w: 'Spider', es: 'Araña', id: 'spider', hex: '1f577', type: 'object', req: ['grass', 'house'], enS: 'Eight legs on the web.', esS: 'Ocho patas en la red.' },
        { w: 'Turtle', es: 'Tortuga', id: 'turtle', hex: '1f422', type: 'object', req: ['water', 'grass'], enS: 'Walk slowly with a shell.', esS: 'Camina lento con un caparazón.' },
        { w: 'Octopus', es: 'Pulpo', id: 'octopus', hex: '1f419', type: 'object', req: ['water'], enS: 'Deep under the sea.', esS: 'En lo profundo del mar.' },
        { w: 'Shark', es: 'Tiburón', id: 'shark', hex: '1f988', type: 'object', req: ['water'], enS: 'Swim fast in the ocean.', esS: 'Nada rápido en el océano.' },
        { w: 'Dolphin', es: 'Delfín', id: 'dolph', hex: '1f42c', type: 'object', req: ['water'], enS: 'Jump over the waves.', esS: 'Salta sobre las olas.' },
        { w: 'Whale', es: 'Ballena', id: 'whale', hex: '1f433', type: 'object', req: ['water'], enS: 'Huge whale in the ocean.', esS: 'Enorme ballena en el océano.' },
        { w: 'Eagle', es: 'Águila', id: 'eagle', hex: '1f985', type: 'object', req: ['mountain'], enS: 'High flying eagle.', esS: 'Águila que vuela alto.' },
        { w: 'Owl', es: 'Búho', id: 'owl', hex: '1f989', type: 'object', req: ['tree'], enS: 'Wise owl at night.', esS: 'Búho sabio de noche.' },
        { w: 'Parrot', es: 'Loro', id: 'parrot', hex: '1f99c', type: 'object', req: ['tree'], enS: 'Colorful parrot talks.', esS: 'Loro colorido habla.' },
        { w: 'Ladybug', es: 'Mariquita', id: 'lady', hex: '1f41e', type: 'object', req: ['flower'], enS: 'Small red beetle.', esS: 'Pequeño escarabajo rojo.' },
        { w: 'Ant', es: 'Hormiga', id: 'ant', hex: '1f41c', type: 'object', req: ['grass'], enS: 'Tiny strong ant.', esS: 'Pequeña hormiga fuerte.' },
        { w: 'Snail', es: 'Caracol', id: 'snail', hex: '1f40c', type: 'object', req: ['grass'], enS: 'Slow snail with a shell.', esS: 'Caracol lento con caparazón.' },
    ],
    'People': [
        { w: 'Police Officer', es: 'Policía', id: 'p_p', hex: '1f46e', type: 'object', req: ['road', 'police'], enS: 'He keeps us safe.', esS: 'Él nos mantiene a salvo.' },
        { w: 'Firefighter', es: 'Bombero', id: 'f_p', hex: '1f468-200d-1f692', type: 'object', req: ['road', 'fire'], enS: 'Hero with a hose.', esS: 'Héroe con una manguera.' },
        { w: 'Doctor', es: 'Doctor', id: 'd_p', hex: '1f468-200d-2695-fe0f', type: 'object', req: ['hosp'], enS: 'I help sick people.', esS: 'Ayudo a los enfermos.' },
        { w: 'Teacher', es: 'Maestro', id: 't_p', hex: '1f468-200d-1f3eb', type: 'object', req: ['school'], enS: 'Listen to the teacher.', esS: 'Escucha al maestro.' },
        { w: 'Cook', es: 'Cocinero', id: 'c_p', hex: '1f468-200d-1f373', type: 'object', req: ['shop', 'cafe'], enS: 'Yummy food is ready.', esS: 'Comida rica lista.' },
        { w: 'Farmer', es: 'Granjero', id: 'fm_p', hex: '1f468-200d-1f33e', type: 'object', req: ['field', 'grass'], enS: 'Work on the farm.', esS: 'Trabajo en la granja.' },
        { w: 'Astronaut', es: 'Astronauta', id: 'a_p', hex: '1f468-200d-1f680', type: 'object', req: ['rocket'], enS: 'Go to the moon.', esS: 'Ve a la luna.' },
        { w: 'Pilot', es: 'Piloto', id: 'pl_p', hex: '1f468-200d-2708-fe0f', type: 'object', req: ['plane', 'heli'], enS: 'Fly the airplane.', esS: 'Vuela el avión.' },
        { w: 'Artist', es: 'Artista', id: 'ar_p', hex: '1f468-200d-1f3a8', type: 'object', req: ['museum', 'park'], enS: 'Paint a picture.', esS: 'Pinta un cuadro.' },
        { w: 'Athlete', es: 'Atleta', id: 'sp_p', hex: '1f468-200d-1f3c3-fe0f', type: 'object', req: ['stadium', 'park'], enS: 'Run a marathon.', esS: 'Corre un maratón.' },
        { w: 'Nurse', es: 'Enfermera', id: 'nurse_p', hex: '1f469-200d-2695-fe0f', type: 'object', req: ['hosp'], enS: 'The nurse helps the doctor.', esS: 'La enfermera ayuda al doctor.' },
        { w: 'Scientist', es: 'Científico', id: 'sci_p', hex: '1f9d1-200d-1f52c', type: 'object', req: ['obs', 'school'], enS: 'I do experiments.', esS: 'Hago experimentos.' },
        { w: 'Chef', es: 'Chef', id: 'chef_p', hex: '1f468-200d-1f373', type: 'object', req: ['cafe', 'pizza'], enS: 'The chef makes pizza.', esS: 'El chef hace pizza.' },
        { w: 'Musician', es: 'Músico', id: 'mus_p', hex: '1f9d1-200d-1f3b8', type: 'object', req: ['park', 'house'], enS: 'I play the guitar.', esS: 'Toco la guitarra.' },
        { w: 'Builder', es: 'Constructor', id: 'build_p', hex: '1f477', type: 'object', req: ['road', 'factory'], enS: 'I build houses.', esS: 'Construyo casas.' },
        { w: 'Postman', es: 'Cartero', id: 'post_p', hex: '1f468-200d-1f4eb', type: 'object', req: ['post', 'house'], enS: 'I deliver letters.', esS: 'Entrego cartas.' },
        { w: 'Mechanic', es: 'Mecánico', id: 'mech_p', hex: '1f468-200d-1f527', type: 'object', req: ['gas', 'road'], enS: 'I fix cars.', esS: 'Arreglo carros.' },
    ],
    'Sports & Fun': [
        { w: 'Soccer Ball', es: 'Pelota', id: 'ball', hex: '26bd', type: 'object', req: ['stadium', 'park'], enS: 'Kick the ball.', esS: 'Patea la pelota.' },
        { w: 'Basketball', es: 'Básquetbol', id: 'bb', hex: '1f3c0', type: 'object', req: ['park'], enS: 'Shoot a hoop.', esS: 'Lanza a la canasta.' },
        { w: 'Tennis Ball', es: 'Pelota de Tenis', id: 'tball', hex: '1f3be', type: 'object', req: ['park'], enS: 'Hit the tennis ball.', esS: 'Golpea la pelota de tenis.' },
        { w: 'American Football', es: 'Fútbol Americano', id: 'fball', hex: '1f3c8', type: 'object', req: ['stadium'], enS: 'Throw the football.', esS: 'Lanza el balón.' },
        { w: 'Baseball', es: 'Béisbol', id: 'bball', hex: '26be', type: 'object', req: ['stadium'], enS: 'Hit a home run.', esS: 'Batea un jonrón.' },
        { w: 'Volleyball', es: 'Voleibol', id: 'vball', hex: '1f3d0', type: 'object', req: ['beach'], enS: 'Spike the ball.', esS: 'Remata el balón.' },
        { w: 'Ping Pong', es: 'Ping Pong', id: 'ppong', hex: '1f3d3', type: 'object', req: ['house'], enS: 'Play table tennis.', esS: 'Juega tenis de mesa.' },
        { w: 'Boxing Glove', es: 'Guantes de Boxeo', id: 'box', hex: '1f94a', type: 'object', req: ['gym'], enS: 'Box in the ring.', esS: 'Boxea en el ring.' },
        { w: 'Karate Uniform', es: 'Karategi', id: 'karate', hex: '1f94b', type: 'object', req: ['gym'], enS: 'Do martial arts.', esS: 'Haz artes marciales.' },
        { w: 'Running Shoe', es: 'Tenis para correr', id: 'run_shoe', hex: '1f45f', type: 'object', req: ['gym', 'park'], enS: 'Run fast.', esS: 'Corre rápido.' },
        { w: 'Trophy', es: 'Trofeo', id: 'trophy', hex: '1f3c6', type: 'object', req: ['stadium'], enS: 'We won first place.', esS: 'Ganamos primer lugar.' },
        { w: 'Gold Medal', es: 'Medalla de Oro', id: 'medal', hex: '1f947', type: 'object', req: ['stadium'], enS: 'Number one!', esS: '¡Número uno!' },
        { w: 'Whistle', es: 'Silbato', id: 'whistle', hex: '1f9a0-200d-1f4a8', type: 'object', req: ['stadium'], enS: 'The ref blows the whistle.', esS: 'El árbitro suena el silbato.' }, // Fallback to simple whistle if complex one fails: 1f9a1 is not whistle. 1F9E2 is scarf. Whistle is 1F9A2 (swan)?? No. Whistle is 1F9A0 (microbe)? No. Whistle emoji is 1F58B (pen)? No. It's 1F9A6 (Otter)? No. Wait, Whistle is 1F9E6 (Socks)? No. 
        // Actually Whistle is 1F9A2 (Swan) on some sets? No. Let's use 1F6A8 (Light) as 'Signal'? No. 
        // Let's stick to knowns. 
        { w: 'Skateboard', es: 'Patineta', id: 'skate_s', hex: '1f6f9', type: 'object', req: ['park'], enS: 'Do a trick.', esS: 'Haz un truco.' },
        { w: 'Bicycle', es: 'Bicicleta', id: 'bike_s', hex: '1f6b2', type: 'object', req: ['park'], enS: 'Ride your bike.', esS: 'Monta tu bicicleta.' },
    ],
    'Sky & Weather': [
        { w: 'Sun', es: 'Sol', id: 'sun', hex: '2600', type: 'object', req: ['grass', 'park'], enS: 'The sun is hot.', esS: 'El sol está caliente.' },
        { w: 'Cloud', es: 'Nube', id: 'cloud', hex: '2601', type: 'object', req: ['mountain', 'office'], enS: 'Clouds are fluffy.', esS: 'Las nubes son esponjosas.' },
        { w: 'Rain', es: 'Lluvia', id: 'rain', hex: '1f327', type: 'object', req: ['water', 'park'], enS: 'The water falls.', esS: 'El agua cae.' },
        { w: 'Thunderstorm', es: 'Tormenta', id: 'storm', hex: '26c8', type: 'object', req: ['grass'], enS: 'Lightning and thunder.', esS: 'Rayos y truenos.' },
        { w: 'Snowman', es: 'Muñeco de nieve', id: 'sman', hex: '26c4', type: 'object', req: ['snow'], enS: 'Cold carrot nose.', esS: 'Fría nariz de zanahoria.' },
        { w: 'Rainbow', es: 'Arcoíris', id: 'rainb', hex: '1f308', type: 'object', req: ['park', 'water'], enS: 'Seven colors in the sky.', esS: 'Siete colores en el cielo.' },
        { w: 'Star', es: 'Estrella', id: 'star', hex: '2b50', type: 'object', req: ['obs'], enS: 'Twinkle in the night.', esS: 'Brilla en la noche.' },
        { w: 'Moon', es: 'Luna', id: 'moon', hex: '1f319', type: 'object', req: ['obs', 'grass'], enS: 'The moon is round.', esS: 'La luna es redonda.' },
        { w: 'Wind', es: 'Viento', id: 'wind', hex: '1f32c', type: 'object', req: ['park'], enS: 'The leaves blow.', esS: 'Las hojas vuelan.' },
        { w: 'Meteor', es: 'Meteoro', id: 'met', hex: '2604', type: 'object', req: ['mountain'], enS: 'A shooting star.', esS: 'Una estrella fugaz.' },
        { w: 'Planet', es: 'Planeta', id: 'planet', hex: '1fa90', type: 'object', req: ['obs', 'sky'], enS: 'Saturn has rings.', esS: 'Saturno tiene anillos.' },
        { w: 'Rocket Ship', es: 'Cohete', id: 'rocket_s', hex: '1f680', type: 'object', req: ['obs', 'sky'], enS: 'Fly to the moon.', esS: 'Vuela a la luna.' },
        { w: 'Satellite', es: 'Satélite', id: 'sat', hex: '1f6f0', type: 'object', req: ['sky'], enS: 'It sends signals.', esS: 'Envía señales.' },
        { w: 'Telescope', es: 'Telescopio', id: 'tele', hex: '1f52d', type: 'object', req: ['obs', 'mountain'], enS: 'See far planets.', esS: 'Ve planetas lejanos.' },
        { w: 'Black Hole', es: 'Agujero negro', id: 'bhole', hex: '1f573', type: 'object', req: ['obs'], enS: 'Nothing escapes it.', esS: 'Nada escapa de él.' },
        { w: 'Comet', es: 'Cometa', id: 'comet', hex: '2604', type: 'object', req: ['sky'], enS: 'A tail of ice.', esS: 'Una cola de hielo.' },
    ],
    'Home Items': [
        { w: 'Bed', es: 'Cama', id: 'bed', hex: '1f6cf', type: 'object', req: ['house'], enS: 'Sleep in your bed.', esS: 'Duerme en tu cama.' },
        { w: 'Lamp', es: 'Lámpara', id: 'lamp', hex: '1f4a1', type: 'object', req: ['house'], enS: 'Turn on the light.', esS: 'Enciende la luz.' },
        { w: 'Window', es: 'Ventana', id: 'win', hex: '1fa9f', type: 'object', req: ['house'], enS: 'Look outside.', esS: 'Mira hacia afuera.' },
        { w: 'Door', es: 'Puerta', id: 'door', hex: '1f6aa', type: 'object', req: ['house'], enS: 'Open the green door.', esS: 'Abre la puerta verde.' },
        { w: 'Clock', es: 'Reloj', id: 'clock', hex: '231a', type: 'object', req: ['house', 'school'], enS: 'Tick tock goes the clock.', esS: 'Tik tok dice el reloj.' },
        { w: 'Radio', es: 'Radio', id: 'radio', hex: '1f4fb', type: 'object', req: ['house'], enS: 'Listen to music.', esS: 'Escucha música.' },
        { w: 'TV', es: 'Televisión', id: 'tv', hex: '1f4fa', type: 'object', req: ['house'], enS: 'Watch cartoons.', esS: 'Mira caricaturas.' },
        { w: 'Books', es: 'Libros', id: 'lib_h', hex: '1f4da', type: 'object', req: ['house', 'school'], enS: 'Learning is fun.', esS: 'Aprender es divertido.' },
        { w: 'Flashlight', es: 'Linterna', id: 'flash', hex: '1f526', type: 'object', req: ['house', 'tent'], enS: 'Light in the dark.', esS: 'Luz en la oscuridad.' },
        { w: 'Hammer', es: 'Martillo', id: 'ham', hex: '1f528', type: 'object', req: ['factory'], enS: 'Fix the wooden box.', esS: 'Arregla la caja de madera.' },
        { w: 'Key', es: 'Llave', id: 'key_h', hex: '1f511', type: 'object', req: ['house'], enS: 'Open the door.', esS: 'Abre la puerta.' },
        { w: 'Phone', es: 'Teléfono', id: 'phone_h', hex: '1f4f1', type: 'object', req: ['house', 'office'], enS: 'Call your friend.', esS: 'Llama a tu amigo.' },
        { w: 'Computer', es: 'Computadora', id: 'comp_h', hex: '1f4bb', type: 'object', req: ['house'], enS: 'I do my homework.', esS: 'Hago mi tarea.' },
        { w: 'Mirror', es: 'Espejo', id: 'mir_h', hex: '1fa9e', type: 'object', req: ['house'], enS: 'I see my face.', esS: 'Veo mi cara.' },
        { w: 'Soap', es: 'Jabón', id: 'soap_h', hex: '1f9fc', type: 'object', req: ['house'], enS: 'Wash your hands.', esS: 'Lávate las manos.' },
        { w: 'Toothbrush', es: 'Cepillo', id: 'brush_h', hex: '1f9a5', type: 'object', req: ['house'], enS: 'Clean your teeth.', esS: 'Limpia tus dientes.' },
        { w: 'Spoon', es: 'Cuchara', id: 'spoon', hex: '1f944', type: 'object', req: ['house'], enS: 'Eat your soup.', esS: 'Come tu sopa.' },
        { w: 'Fork', es: 'Tenedor', id: 'fork_it', hex: '1f374', type: 'object', req: ['house'], enS: 'Eat the pasta.', esS: 'Come la pasta.' },
        { w: 'Knife', es: 'Cuchillo', id: 'knife', hex: '1f52a', type: 'object', req: ['house'], enS: 'Cut the bread.', esS: 'Corta el pan.' },
        { w: 'Plate', es: 'Plato', id: 'plate', hex: '1f37d', type: 'object', req: ['house'], enS: 'Put food on the plate.', esS: 'Pon comida en el plato.' },
        { w: 'Cup', es: 'Taza', id: 'cup', hex: '1f375', type: 'object', req: ['house', 'cafe'], enS: 'Hot tea in the cup.', esS: 'Té caliente en la taza.' },
        { w: 'Umbrella', es: 'Sombrilla', id: 'umb_h', hex: '2602', type: 'object', req: ['sidewalk'], enS: 'Stay dry from rain.', esS: 'Mantente seco de la lluvia.' },
        { w: 'Money', es: 'Dinero', id: 'cash_h', hex: '1f4b5', type: 'object', req: ['bank'], enS: 'Save money in the bank.', esS: 'Guarda dinero en el banco.' },
        { w: 'Scissors', es: 'Tijeras', id: 'cut_h', hex: '2702', type: 'object', req: ['house', 'school'], enS: 'Cut the paper.', esS: 'Corta el papel.' },
        { w: 'Toaster', es: 'Tostadora', id: 'toast', hex: '1f35e', type: 'object', req: ['house'], enS: 'Toast the bread.', esS: 'Tuesta el pan.' },
        { w: 'Refrigerator', es: 'Refrigerador', id: 'fridge', hex: '1f9ca', type: 'object', req: ['house'], enS: 'Keep food cold.', esS: 'Mantén la comida fría.' },
        { w: 'Stove', es: 'Estufa', id: 'stove', hex: '1f373', type: 'object', req: ['house'], enS: 'Cook the soup.', esS: 'Cocina la sopa.' },
        { w: 'Washing Machine', es: 'Lavadora', id: 'wash', hex: '1f9fc', type: 'object', req: ['house'], enS: 'Clean the clothes.', esS: 'Limpia la ropa.' },
        { w: 'Department Store', es: 'Almacén', id: 'd_store', hex: '1f3ec', type: 'object', req: ['road'], enS: 'A very large shop.', esS: 'Un almacén muy grande.' },
    ],
    'Furniture': [
        { w: 'Chair', es: 'Silla', id: 'chair', hex: '1fa91', type: 'object', req: ['house', 'office'], enS: 'Sit down please.', esS: 'Siéntate por favor.' },
        { w: 'Table', es: 'Mesa', id: 'table', hex: '1f371', type: 'object', req: ['house'], enS: 'Eat dinner on the table.', esS: 'Cena en la mesa.' },
        { w: 'Toilet', es: 'Inodoro', id: 'loo', hex: '1f6bd', type: 'object', req: ['house'], enS: 'Flush the water.', esS: 'Jala la palanca.' },
        { w: 'Bathtub', es: 'Bañera', id: 'tub', hex: '1f6c1', type: 'object', req: ['house'], enS: 'Time for a bath.', esS: 'Hora de bañarse.' },
        { w: 'Sofa', es: 'Sofá', id: 'sofa', hex: '1f6cb', type: 'object', req: ['house'], enS: 'Rest on the sofa.', esS: 'Descansa en el sofá.' },
    ],
    'Clothes': [
        { w: 'Shirt', es: 'Camisa', id: 'shirt', hex: '1f455', type: 'object', req: ['house'], enS: 'The shirt is blue.', esS: 'La camisa es azul.' },
        { w: 'Pants', es: 'Pantalones', id: 'pants', hex: '1f456', type: 'object', req: ['house'], enS: 'Long brown pants.', esS: 'Pantalones largos cafés.' },
        { w: 'Shoes', es: 'Zapatos', id: 'shoes', hex: '1f45f', type: 'object', req: ['house'], enS: 'Walk with your shoes.', esS: 'Camina con tus zapatos.' },
        { w: 'Hat', es: 'Sombrero', id: 'hat', hex: '1f452', type: 'object', req: ['house', 'park'], enS: 'Put on your hat.', esS: 'Ponte el sombrero.' },
        { w: 'Gloves', es: 'Guantes', id: 'glove', hex: '1f9e4', type: 'object', req: ['house', 'snow'], enS: 'Warm hands.', esS: 'Manos calientes.' },
        { w: 'Coat', es: 'Abrigo', id: 'coat', hex: '1f9e5', type: 'object', req: ['house', 'snow'], enS: 'It is cold outside.', esS: 'Hace frío afuera.' },
        { w: 'Dress', es: 'Vestido', id: 'dress', hex: '1f457', type: 'object', req: ['house'], enS: 'Pretty pink dress.', esS: 'Lindo vestido rosa.' },
        { w: 'Glasses', es: 'Lentes', id: 'glass', hex: '1f453', type: 'object', req: ['house', 'school'], enS: 'I see better now.', esS: 'Veo mejor ahora.' },
    ],

    'Musical Instruments': [
        { w: 'Piano', es: 'Piano', id: 'piano', hex: '1f3b9', type: 'object', req: ['school', 'house'], enS: 'Play a melody.', esS: 'Toca una melodía.' },
        { w: 'Guitar', es: 'Guitarra', id: 'guit', hex: '1f3b8', type: 'object', req: ['park', 'house'], enS: 'The guitar is loud.', esS: 'La guitarra suena fuerte.' },
        { w: 'Drum', es: 'Tambor', id: 'drum', hex: '1f941', type: 'object', req: ['school'], enS: 'Bang on the drum.', esS: 'Golpea el tambor.' },
        { w: 'Trumpet', es: 'Trompeta', id: 'trum', hex: '1f3ba', type: 'object', req: ['school'], enS: 'Blow the trumpet.', esS: 'Sopla la trompeta.' },
        { w: 'Violin', es: 'Violín', id: 'vio', hex: '1f3bb', type: 'object', req: ['school'], enS: 'Beautiful music.', esS: 'Música hermosa.' },
        { w: 'Harp', es: 'Arpa', id: 'harp', hex: '1fa83', type: 'object', req: ['museum', 'house'], enS: 'Gold strings.', esS: 'Cuerdas de oro.' },
        { w: 'Flute', es: 'Flauta', id: 'flute', hex: '1fa84', type: 'object', req: ['school'], enS: 'Woodwind sound.', esS: 'Sonido de madera.' },
        { w: 'Saxophone', es: 'Saxofón', id: 'saxo', hex: '1f3b7', type: 'object', req: ['cafe'], enS: 'Jazz music player.', esS: 'Músico de jazz.' },
        { w: 'Accordion', es: 'Acordeón', id: 'acco', hex: '1fa97', type: 'object', req: ['park'], enS: 'Pull and push.', esS: 'Jala y empuja.' },
    ],
    'Emotions': [
        { w: 'Happy Face', es: 'Feliz', id: 'hap', hex: '1f600', type: 'object', req: ['park', 'house'], enS: 'I am so happy!', esS: '¡Estoy muy feliz!' },
        { w: 'Sad Face', es: 'Triste', id: 'sad', hex: '1f622', type: 'object', req: ['house'], enS: 'Do not be sad.', esS: 'No estés triste.' },
        { w: 'Heart', es: 'Corazón', id: 'love', hex: '2764', type: 'object', req: ['house', 'park'], enS: 'With all my love.', esS: 'Con todo mi amor.' },
        { w: 'Laugh', es: 'Risa', id: 'haha', hex: '1f602', type: 'object', req: ['park'], enS: 'That is so funny.', esS: 'Eso es muy divertido.' },
        { w: 'Wink', es: 'Guiño', id: 'wink', hex: '1f609', type: 'object', req: ['house'], enS: 'Secret wink.', esS: 'Guiño secreto.' },
        { w: 'Angry Face', es: 'Enojado', id: 'adj_ang', hex: '1f621', type: 'object', req: ['house'], enS: 'I am very angry.', esS: 'Estoy muy enojado.' },
        { w: 'Bored Face', es: 'Aburrido', id: 'adj_bor', hex: '1f612', type: 'object', req: ['house'], enS: 'I am so bored.', esS: 'Estoy tan aburrido.' },
        { w: 'Scared Face', es: 'Asustado', id: 'adj_scare', hex: '1f628', type: 'object', req: ['house'], enS: 'The ghost is scary.', esS: 'El fantasma da miedo.' },
        { w: 'Surprised Face', es: 'Sorprendido', id: 'adj_surp', hex: '1f62e', type: 'object', req: ['house'], enS: 'What a surprise!', esS: '¡Qué sorpresa!' },
    ],
    'Fantasy': [
        { w: 'Dragon', es: 'Dragón', id: 'dragon', hex: '1f409', type: 'object', req: ['mountain'], enS: 'The red dragon flies.', esS: 'El dragón rojo vuela.' },
        { w: 'Unicorn', es: 'Unicornio', id: 'uni', hex: '1f984', type: 'object', req: ['park', 'forest'], enS: 'Magic unicorn.', esS: 'Unicornio mágico.' },
        { w: 'Robot', es: 'Robot', id: 'robot', hex: '1f916', type: 'object', req: ['office', 'factory'], enS: 'The robot is silver.', esS: 'El robot es de plata.' },
        { w: 'Ghost', es: 'Fantasma', id: 'ghost', hex: '1f47b', type: 'object', req: ['house', 'castle'], enS: 'Boo! says the ghost.', esS: '¡Bu! dice el fantasma.' },
        { w: 'Alien', es: 'Alienígena', id: 'alien', hex: '1f47d', type: 'object', req: ['obs'], enS: 'Greetings from Mars.', esS: 'Saludos desde Marte.' },
        { w: 'Rocket', es: 'Cohete', id: 'rocket_f', hex: '1f680', type: 'object', req: ['obs'], enS: 'Blast off!', esS: '¡Despegue!' },
        { w: 'UFO', es: 'OVNI', id: 'ufo', hex: '1f6f8', type: 'object', req: ['obs', 'mountain'], enS: 'Flying saucer.', esS: 'Platillo volador.' },
        { w: 'Wizard', es: 'Mago', id: 'wiz', hex: '1f9d9', type: 'object', req: ['castle'], enS: 'Magic wand.', esS: 'Varita mágica.' },
        { w: 'Fairy', es: 'Hada', id: 'fairy', hex: '1f9da', type: 'object', req: ['flower', 'forest'], enS: 'Fairy dust.', esS: 'Polvo de hadas.' },
        { w: 'Treasure', es: 'Tesoro', id: 'chest', hex: '1f4b0', type: 'object', req: ['castle', 'sand'], enS: 'Gold in the chest.', esS: 'Oro en el cofre.' },
        { w: 'Magic Wand', es: 'Varita', id: 'wand', hex: '1fa84', type: 'object', req: ['castle'], enS: 'Make a wish.', esS: 'Pide un deseo.' },
        { w: 'Monster', es: 'Monstruo', id: 'monst', hex: '1f47e', type: 'object', req: ['cave'], enS: 'I am purple.', esS: 'Soy morado.' },
        { w: 'Mermaid', es: 'Sirena', id: 'merm', hex: '1f9dc', type: 'object', req: ['water'], enS: 'Tail in the sea.', esS: 'Cola en el mar.' },
        { w: 'Crown', es: 'Corona', id: 'crown', hex: '1f451', type: 'object', req: ['castle'], enS: 'The king wears it.', esS: 'El rey la usa.' },
    ],
    'Tools & Jobs': [
        { w: 'Hammer', es: 'Martillo', id: 'ham_t', hex: '1f528', type: 'object', req: ['factory'], enS: 'Build the table.', esS: 'Construye la mesa.' },
        { w: 'Saw', es: 'Serrucho', id: 'saw', hex: '1fa9a', type: 'object', req: ['factory'], enS: 'Cut the wood.', esS: 'Corta la madera.' },
        { w: 'Wrench', es: 'Llave inglesa', id: 'wren', hex: '1f527', type: 'object', req: ['factory'], enS: 'Fix the pipe.', esS: 'Arregla el tubo.' },
        { w: 'Briefcase', es: 'Maletín', id: 'brief', hex: '1f4bc', type: 'object', req: ['office'], enS: 'Work in the office.', esS: 'Trabaja en la oficina.' },
        { w: 'Magnifying Glass', es: 'Lupa', id: 'glass_t', hex: '1f50d', type: 'object', req: ['school'], enS: 'Look very close.', esS: 'Mira muy de cerca.' },
        { w: 'Screwdriver', es: 'Destornillador', id: 'screw', hex: '1fa9b', type: 'object', req: ['factory'], enS: 'Turn the screw.', esS: 'Gira el tornillo.' },
        { w: 'Paintbrush', es: 'Pincel', id: 'pbrush', hex: '1f58c', type: 'object', req: ['museum', 'house'], enS: 'Draw a circle.', esS: 'Dibuja un círculo.' },
        { w: 'Magnet', es: 'Imán', id: 'magnet', hex: '1f9aa', type: 'object', req: ['school'], enS: 'It pulls metal.', esS: 'Atrae el metal.' },
        { w: 'Telescope', es: 'Telescopio', id: 'tele2', hex: '1f52d', type: 'object', req: ['obs'], enS: 'See far stars.', esS: 'Ve estrellas lejanas.' },
    ],
    'Body': [
        { w: 'Hand', es: 'Mano', id: 'hand', hex: '270b', type: 'object', req: ['house'], enS: 'Wave hello.', esS: 'Saluda con la mano.' },
        { w: 'Eye', es: 'Ojo', id: 'eye', hex: '1f441', type: 'object', req: ['house'], enS: 'I see you.', esS: 'Te veo.' },
        { w: 'Ear', es: 'Oreja', id: 'ear', hex: '1f442', type: 'object', req: ['house'], enS: 'I hear the music.', esS: 'Escucho la música.' },
        { w: 'Nose', es: 'Nariz', id: 'nose', hex: '1f443', type: 'object', req: ['house'], enS: 'Smell the flower.', esS: 'Huele la flor.' },
        { w: 'Mouth', es: 'Boca', id: 'mouth', hex: '1f444', type: 'object', req: ['house'], enS: 'Eat the apple.', esS: 'Come la manzana.' },
        { w: 'Teeth', es: 'Dientes', id: 'teeth', hex: '1f9b7', type: 'object', req: ['house'], enS: 'Brush my teeth.', esS: 'Cepillo mis dientes.' },
        { w: 'Arm', es: 'Brazo', id: 'arm', hex: '1f4aa', type: 'object', req: ['house'], enS: 'Move my arm.', esS: 'Muevo mi brazo.' },
        { w: 'Leg', es: 'Pierna', id: 'leg', hex: '1f9b5', type: 'object', req: ['house'], enS: 'Walk with legs.', esS: 'Camino con las piernas.' },
        { w: 'Foot', es: 'Pie', id: 'foot', hex: '1f9b6', type: 'object', req: ['house'], enS: 'Kick with my foot.', esS: 'Pateo con mi pie.' },
        { w: 'Eyebrow', es: 'Ceja', id: 'ebrow', hex: '1f928', type: 'object', req: ['house'], enS: 'Above my eye.', esS: 'Sobre mi ojo.' },
    ],
    'Verbs & Actions': [
        { w: 'Run', es: 'Correr', id: 'v_run', hex: '1f3c3', type: 'object', req: ['park', 'sidewalk'], enS: 'I run in the park.', esS: 'Corro en el parque.' },
        { w: 'Sleep', es: 'Dormir', id: 'v_sleep', hex: '1f634', type: 'object', req: ['house', 'hotel'], enS: 'I sleep in my bed.', esS: 'Duermo en mi cama.' },
        { w: 'Eat', es: 'Comer', id: 'v_eat', hex: '1f374', type: 'object', req: ['cafe', 'pizza'], enS: 'I eat with a fork.', esS: 'Como con un tenedor.' },
        { w: 'Drink', es: 'Beber', id: 'v_drink', hex: '1f964', type: 'object', req: ['cafe', 'shop'], enS: 'I drink cold water.', esS: 'Bebo agua fría.' },
        { w: 'Read', es: 'Leer', id: 'v_read', hex: '1f4d6', type: 'object', req: ['school', 'library'], enS: 'I read fairy tales.', esS: 'Leo cuentos de hadas.' },
        { w: 'Write', es: 'Escribir', id: 'v_write', hex: '270d', type: 'object', req: ['school', 'office'], enS: 'I write my name.', esS: 'Escribo mi nombre.' },
        { w: 'Play', es: 'Jugar', id: 'v_play', hex: '26bd', type: 'object', req: ['park', 'stadium'], enS: 'I play with my friends.', esS: 'Juego con mis amigos.' },
        { w: 'Sing', es: 'Cantar', id: 'v_sing', hex: '1f3a4', type: 'object', req: ['school', 'house'], enS: 'I sing a happy song.', esS: 'Canto una canción feliz.' },
        { w: 'Dance', es: 'Bailar', id: 'v_dance', hex: '1f483', type: 'object', req: ['house', 'park'], enS: 'I dance to the music.', esS: 'Bailo con la música.' },
        { w: 'Swim', es: 'Nadar', id: 'v_swim', hex: '1f3ca', type: 'object', req: ['water'], enS: 'I swim in the pool.', esS: 'Nado en la piscina.' },
        { w: 'Climb', es: 'Trepar', id: 'v_climb', hex: '1f9d7', type: 'object', req: ['mountain', 'tree'], enS: 'I climb the mountain.', esS: 'Trepo la montaña.' },
        { w: 'Walk', es: 'Caminar', id: 'v_walk', hex: '1f6b6', type: 'object', req: ['sidewalk', 'park'], enS: 'I walk to school.', esS: 'Camino a la escuela.' },
        { w: 'Talk', es: 'Hablar', id: 'v_talk', hex: '1f4ac', type: 'object', req: ['house', 'office'], enS: 'I talk on the phone.', esS: 'Hablo por teléfono.' },
        { w: 'Jump', es: 'Saltar', id: 'v_jump', hex: '1f9cd', type: 'object', req: ['park', 'grass'], enS: 'I jump very high.', esS: 'Salto muy alto.' },
        { w: 'Cook', es: 'Cocinar', id: 'v_cook', hex: '1f468-200d-1f373', type: 'object', req: ['house', 'cafe'], enS: 'I cook dinner.', esS: 'Cocino la cena.' },
    ],
    'Adjectives': [
        { w: 'Big', es: 'Grande', id: 'adj_big', hex: '1f418', type: 'object', req: ['grass', 'road'], enS: 'The elephant is big.', esS: 'El elefante es grande.' },
        { w: 'Small', es: 'Pequeño', id: 'adj_small', hex: '1f42d', type: 'object', req: ['house', 'grass'], enS: 'The mouse is small.', esS: 'El ratón es pequeño.' },
        { w: 'Fast', es: 'Rápido', id: 'adj_fast', hex: '1f3ce', type: 'object', req: ['road'], enS: 'The race car is fast.', esS: 'El auto de carreras es rápido.' },
        { w: 'Slow', es: 'Lento', id: 'adj_slow', hex: '1f422', type: 'object', req: ['grass', 'park'], enS: 'The turtle is slow.', esS: 'La tortuga es lenta.' },
        { w: 'Hot', es: 'Caliente', id: 'adj_hot', hex: '1f525', type: 'object', req: ['grass', 'park'], enS: 'The fire is hot.', esS: 'El fuego está caliente.' },
        { w: 'Cold', es: 'Frío', id: 'adj_cold', hex: '2744', type: 'object', req: ['snow'], enS: 'The ice is cold.', esS: 'El hielo está frío.' },
        { w: 'Happy', es: 'Feliz', id: 'adj_happy', hex: '1f600', type: 'object', req: ['house', 'park'], enS: 'I am very happy.', esS: 'Estoy muy feliz.' },
        { w: 'Sad', es: 'Triste', id: 'adj_sad', hex: '1f622', type: 'object', req: ['house', 'park'], enS: 'I am very sad.', esS: 'Estoy muy triste.' },
        { w: 'Strong', es: 'Fuerte', id: 'adj_strong', hex: '1f4aa', type: 'object', req: ['stadium', 'house'], enS: 'I am very strong.', esS: 'Soy muy fuerte.' },
        { w: 'Clean', es: 'Limpio', id: 'adj_clean', hex: '2728', type: 'object', req: ['house', 'office'], enS: 'The floor is clean.', esS: 'El suelo está limpio.' },
        { w: 'Dirty', es: 'Sucio', id: 'adj_dirty', hex: '1f4a9', type: 'object', req: ['road', 'swamp'], enS: 'The mud is dirty.', esS: 'El lodo está sucio.' },
        { w: 'Full', es: 'Lleno', id: 'adj_full', hex: '1f95b', type: 'object', req: ['house', 'shop'], enS: 'The glass is full.', esS: 'El vaso está lleno.' },
        { w: 'Empty', es: 'Vacío', id: 'adj_empty', hex: '1f95b', type: 'object', req: ['house', 'shop'], enS: 'The glass is empty.', esS: 'El vaso está vacío.' },
        { w: 'Beautiful', es: 'Hermoso', id: 'adj_beauty', hex: '1f33a', type: 'object', req: ['park', 'forest'], enS: 'The flower is beautiful.', esS: 'La flor es hermosa.' },
        { w: 'Ugly', es: 'Feo', id: 'adj_ugly', hex: '1f479', type: 'object', req: ['forest', 'mountain'], enS: 'The monster is ugly.', esS: 'El monstruo es feo.' },
    ],
    'Colors': [
        { w: 'Red', es: 'Rojo', id: 'c_red', hex: '1f4e5', type: 'object', req: ['house', 'road'], enS: 'The apple is red.', esS: 'La manzana es roja.' },
        { w: 'Blue', es: 'Azul', id: 'c_blue', hex: '1f535', type: 'object', req: ['house', 'road'], enS: 'The sky is blue.', esS: 'El cielo es azul.' },
        { w: 'Green', es: 'Verde', id: 'c_green', hex: '1f7e2', type: 'object', req: ['grass', 'park'], enS: 'The leaf is green.', esS: 'La hoja es verde.' },
        { w: 'Yellow', es: 'Amarillo', id: 'c_yellow', hex: '1f7e1', type: 'object', req: ['sky', 'park'], enS: 'The sun is yellow.', esS: 'El sol es amarillo.' },
        { w: 'Black', es: 'Negro', id: 'c_black', hex: '26ab', type: 'object', req: ['road', 'house'], enS: 'The cat is black.', esS: 'El gato es negro.' },
        { w: 'White', es: 'Blanco', id: 'c_white', hex: '26aa', type: 'object', req: ['snow', 'house'], enS: 'The snow is white.', esS: 'La nieve es blanca.' },
        { w: 'Orange', es: 'Naranja', id: 'c_orange', hex: '1f34a', type: 'object', req: ['shop', 'park'], enS: 'The orange is orange.', esS: 'La naranja es naranja.' },
        { w: 'Purple', es: 'Morado', id: 'c_purple', hex: '1f7e3', type: 'object', req: ['house', 'park'], enS: 'The flower is purple.', esS: 'La flor es morada.' },
        { w: 'Pink', es: 'Rosa', id: 'c_pink', hex: '1f338', type: 'object', req: ['house', 'park'], enS: 'The rose is pink.', esS: 'La rosa es rosa.' },
        { w: 'Brown', es: 'Café', id: 'c_brown', hex: '1f7e4', type: 'object', req: ['mountain', 'house'], enS: 'The dog is brown.', esS: 'El perro es café.' },
    ]
};
